
generate_knowledge_triples_hotpotqa_examplars = [
    # 1 - 5
    {
        "title": "Heinrich von B\u00fclow (Grotekop)",
        "text": "Heinrich von B\u00fclow also known as Big Top (Grotekop) was a knight born in the middle of the fourteenth century. He died either before 1395 or during 1415. He prospered as a warrior-supporter of Prince Albrecht of Mecklenburg (and of Sweden). Outside Mecklenberg, Heinrich Grotekop is still remembered in many quarters as an archetypal robber baron on account of his appetite for feuding.", 
        "triples": "<Heinrich von B\u00fclow (Grotekop); also known as; Big Top (Grotekop)>\n<Heinrich von B\u00fclow (Grotekop); born in; middle of the fourteenth century>\n<Heinrich von B\u00fclow (Grotekop); died; before 1395 or during 1415>\n<Heinrich von B\u00fclow (Grotekop); occupation; warrior-supporter>\n<Heinrich von B\u00fclow (Grotekop); supported; Prince Albrecht of Mecklenburg (and of Sweden)>\n<Heinrich von B\u00fclow (Grotekop); remembered as; archetypal robber baron>\n<Heinrich von B\u00fclow (Grotekop); characterized by; appetite for feuding>"
    },
    {
        "title": "All the Way (Craig David song)",
        "text": "\"All the Way\" is the first single released by the British singer Craig David from his third album \"The Story Goes...\". It was the first single he released with new label Warner Bros. Records after Wildstar Records went bankrupt. After missing the top ten with previous singles \"World Filled with Love\" and \"You Don't Miss Your Water ('Til the Well Runs Dry)\", \"All The Way\" returned David to the top three. It was the highest-charting single from \"The Story Goes...\" but not the biggest-selling as \"Don't Love You No More (I'm Sorry)\" spent over double the amount of weeks inside the UK top 75. The music video became the sixth Craig David video directed by Max & Dania.",
        "triples": "<All the Way (Craig David song); first single from the album; The Story Goes...>\n<All the Way (Craig David song); released by; British singer Craig David>\n<All the Way (Craig David song); record label; Warner Bros. Records>\n<All the Way (Craig David song); previous record label; Wildstar Records>\n<All the Way (Craig David song); chart performance; returned to top three>\n<All the Way (Craig David song); highest-charting single from; The Story Goes...>\n<All the Way (Craig David song); not the biggest-selling as; Don't Love You No More (I'm Sorry)>\n<All the Way (Craig David song); director of the music video; Max & Dania>"
    },
    {
        "title": "Chuck Essegian",
        "text": "Charles Abraham \"Chuck\" Essegian (born August 9, 1931) is an American former professional baseball left fielder. He played in Major League Baseball (MLB) the Philadelphia Phillies, St. Louis Cardinals, Los Angeles Dodgers, Baltimore Orioles, Kansas City Athletics, and Cleveland Indians. He also played one season in Nippon Professional Baseball (NPB) for the Kintetsu Buffaloes.",
        "triples": "<Chuck Essegian; full name; Charles Abraham \"Chuck\" Essegian>\n<Chuck Essegian; date of birth; August 9, 1931>\n<Chuck Essegian; nationality; American>\n<Chuck Essegian; occupation; former professional baseball left fielder>\n<Chuck Essegian; played in the league; Major League Baseball (MLB)>\n<Chuck Essegian; played for the teams in MLB; Philadelphia Phillies, St. Louis Cardinals, Los Angeles Dodgers, Baltimore Orioles, Kansas City Athletics, and Cleveland Indians>\n<Chuck Essegian; played one season in the league; Nippon Professional Baseball (NPB)>\n<Chuck Essegian; played for the teams in NPB; Kintetsu Buffaloes>",
    },
    {
        "title": "Pacific International Enterprises",
        "text": "Pacific International Enterprises (PIE) is an American film production company and film distributor, founded by Arthur R. Dubs as a producer of family films. PIE is a privately held company that has been in business for over thirty years as \"\"A Universal Force in Family Film Entertainment\"\". Their films have been continually licensed and re-licensed for television by various channels such as HBO, Disney, TNT, CBS and in over 100 countries worldwide. Many of PIE's movies are filmed on location with outdoor scenery shots such as the state of Oregon in \"Sacred Ground\", the state of Utah in \"Windwalker\" and the state of Colorado for the three films of the \"Wilderness Family\" for example.",
        "triples": "<Pacific International Enterprises; abbreviation; PIE>\n<Pacific International Enterprises; country where the company is based; American>\n<Pacific International Enterprises; types of business; film production and distribution>\n<Pacific International Enterprises; founder; Arthur R. Dubs>\n<Pacific International Enterprises; business structure; privately held company>\n<Pacific International Enterprises; duration of operation; in business for over thirty years>\n<Pacific International Enterprises; slogan; A Universal Force in Family Film Entertainment>\n<Pacific International Enterprises; channels that have licensed the company's films; HBO, Disney, TNT, CBS>\n<Pacific International Enterprises; international reach; over 100 countries worldwide>\n<Pacific International Enterprises; filming locations; Oregon in \"Sacred Ground\", Utah in \"Windwalker\", Colorado in \"Wilderness Family\">", 
    },
    {
        "title": "Farley, New South Wales",
        "text": "Farley is a rural village in the City of Maitland in the Hunter Region of New South Wales, Australia. Early settler Captain Emanuel Hungerford arrived in New South Wales in 1828 before purchasing an established 2000 acre property named Lochdon. Here he built a homestead he called Farley House, from which Farley takes its name, after his ancestral home of Farleigh Hungerford, Somerset. The village is bordered to the north by the Main North railway line, and a station served the surrounding area from 1860 until 1975. The Farley Wastewater Treatment Works is located in a rural area south of the village.",
        "triples": "<Farley, New South Wales; type; rural village>\n<Farley, New South Wales; location; in the City of Maitland in the Hunter Region of New South Wales, Australia>\n<Farley, New South Wales; named after; Farley House>\n<Farley, New South Wales; established by; Captain Emanuel Hungerford>\n<Farley, New South Wales; border; to the north by the Main North railway line>\n<Farley, New South Wales; period during which the station was active; 1860 until 1975>\n<Farley, New South Wales; facility; Farley Wastewater Treatment Works>\n<Farley, New South Wales; facility location; in a rural area south of the village>", 
    },
    # 6 - 10 
    {
        "title": "Nick Perry (writer)",
        "text": "Nick Perry is a British playwright and screenwriter. He is a graduate of the National Film and Television School. His first play Arrivederci Millwall was produced by The Combination at The Albany Empire, Deptford in 1985 and jointly won the Samuel Beckett Award. \"Smallholdings\" was first performed at the Kings Head Theatre in 1986, and \"The Vinegar Fly\" at the Soho Poly in 1988. \"Near Cricket St Thomas, 1919\" was directed by Alan Ayckbourn at the McCarthy Theatre, Scarborough in 1997. \"An Illustrated Talk\" was performed at the Newtown Theatre, Sydney, as part of the 2008 Short and Sweet festival. His radio play \"The Loop\" was broadcast on BBC Radio 4 in November 2009 and won a Sony Radio Academy bronze award. Andrew Scott was named Best Supporting Actor at the inaugural BBC Audio Drama awards in 2012 for his performance in Perry's radio play, \"Referee\".",
        "triples": "<Nick Perry (writer); nationality; British>\n<Nick Perry (writer); occupation; playwright and screenwriter>\n<Nick Perry (writer); education; graduate of the National Film and Television School>\n<Nick Perry (writer); written first play; Arrivederci Millwall>\n<Nick Perry (writer); producer of his first play; The Combination at The Albany Empire, Deptford>\n<Nick Perry (writer); production year of his first play; 1985>\n<Nick Perry (writer); awarded; Samuel Beckett Award for Arrivederci Millwall>\n<Nick Perry (writer); play written by him that was first performed at the Kings Head Theatre in 1986; Smallholdings>\n<Nick Perry (writer); play written by him at the Soho Poly in 1988; The Vinegar Fly>\n<Nick Perry (writer); play written by him that was Alan Ayckbourn at the McCarthy Theatre Scarborough in 1997; Near Cricket St Thomas, 1919>\n<Nick Perry (writer); play written by him that was performed at the Newtown Theatre, Sydney, as part of the 2008 Short and Sweet festival; An Illustrated Talk>\n<Nick Perry (writer); radio play written by him that was broadcast on BBC Radio 4 in November 2009; The Loop>\n<Nick Perry (writer); awarded; Sony Radio Academy bronze award for The Loop>\n<Nick Perry (writer); radio play written by him that was awarded Best Supporting Actor at the inaugural BBC Audio Drama awards in 2012; Referee>",
    },
    {
        "title": "Ellen Glasgow",
        "text": "Ellen Anderson Gholson Glasgow (April 22, 1873 \u2013 November 21, 1945) was an American novelist who portrayed the changing world of the contemporary South.",
        "triples": "<Ellen Glasgow; full name; Ellen Anderson Gholson Glasgow>\n<Ellen Glasgow; date of birth; April 22, 1873>\n<Ellen Glasgow; date of death; November 21, 1945>\n<Ellen Glasgow; nationality; American>\n<Ellen Glasgow; occupation; novelist>\n<Ellen Glasgow; the theme of her literary work; changing world of the contemporary South>", 
    },
    {
        "title": "Morghem's .500 Nitro Express",
        "text": "Morghem's .500 Nitro Express known as Frank's Khing at owner/call name registered events, is a UKC registered male American Pit Bull Terrier. Who competes in dog sports and conformation shows earning titles in Dock Jump, Lure Course, Show Champion, Rally Obedience and Weight Pull. Khing has been awarded the AKC Canine Good Citizen and USTTA temperament tested certifications.",
        "triples": "<Morghem's .500 Nitro Express; also known as; Frank's Khing>\n<Morghem's .500 Nitro Express; registration status; UKC registered>\n<Morghem's .500 Nitro Express; species; male American Pit Bull Terrier>\n<Morghem's .500 Nitro Express; competitions in which he participates; dog sports and conformation shows>\n<Morghem's .500 Nitro Express; titles earned; Dock Jump, Lure Course, Show Champion, Rally Obedience, Weight Pull>\n<Morghem's .500 Nitro Express; awarded; AKC Canine Good Citizen and USTTA temperament tested certifications>", 
    },
    {
        "title": "David Majzlin",
        "text": "David Majzlin is an Emmy\u00ae-nominated composer whose credits include numerous critically acclaimed films such as \"The Loving Story\", \"Youth Knows No Pain\", and \"Sins of My Father\" (\"Pecados De Mi Padre\") for HBO, \"Herb and Dorothy\", \"Stille\", (Winner - Best Score - Avignon Film Festival), \"Being Reel\", (Winner - Grand Prize - Project Greenlight Competition), and \"Shenandoah\" ( Louverture Films, Netflix), directed by Pulitzer Prize-winning photographer, David Turnley. He also wrote additional music for \"Diana Vreeland: The Eye Has To Travel\" (Samuel Goldwyn Films, Venice Film Festival, Toronto International Film Festival), \"Sunshine Cleaning\" (Nomination - Grand Jury Prize - Sundance Film Festival) - starring Amy Adams, Emily Blunt, and Alan Arkin, and source music for \"The Ghost Writer\" (dir., Roman Polanski, starring Ewan McGregor, Pierce Brosnan, Kim Catrall), \"All Good Things\" (dir., Andrew Jarecki, starring Ryan Gosling, Kirsten Dunst, Frank Langella), and \"The Joneses\" (starring Demi Moore, David Duchovny, and Lauren Hutton).",
        "triples": "<David Majzlin; occupation; composer>\n<David Majzlin; recognition; Emmy\u00ae-nominated composer>\n<David Majzlin; notable works he worked with HBO; The Loving Story, Youth Knows No Pain, Sins of My Father (Pecados De Mi Padre)>\n<David Majzlin; notable award-winning works he participated in; Herb and Dorothy, Stille (Winner - Best Score - Avignon Film Festival), Being Reel (Winner - Grand Prize - Project Greenlight Competition), Shenandoah (Louverture Films, Netflix)>\n<David Majzlin; works he wrote additional music for; Diana Vreeland: The Eye Has To Travel (Samuel Goldwyn Films, Venice Film Festival, Toronto International Film Festival), Sunshine Cleaning (Nomination - Grand Jury Prize - Sundance Film Festival)>\n<David Majzlin; works he wrote source music for; The Ghost Writer (dir., Roman Polanski, starring Ewan McGregor, Pierce Brosnan, Kim Catrall), All Good Things (dir., Andrew Jarecki, starring Ryan Gosling, Kirsten Dunst, Frank Langella), The Joneses (starring Demi Moore, David Duchovny, and Lauren Hutton)>", 
    },
    {
        "title": "Todd David Lawhorne",
        "text": "Todd David Lawhorne is an American theatre and film actor. Member of AFTRA and AEA. Best known for his starring role as Dalton Monroe in \"In Plain Sight\" and his supporting role as Phil the skinhead in \"The Bros,\" starring Shaquille O'Neal and Joey Fatone. In New York City, he starred in numerous plays off and off-off Broadway, including \"Twelfth Night\" at Lincoln Center and Laertes in Pineapple Project's production of \"Hamlet.\" Resident actor of the Children's Theatre at the New York Hall of Science.",
        "triples": "<Todd David Lawhorne; nationality; American>\n<Todd David Lawhorne; occupation; theatre and film actor>\n<Todd David Lawhorne; member of; AFTRA and AEA>\n<Todd David Lawhorne; best known for; starring role as Dalton Monroe in \"In Plain Sight\", supporting role as Phil the skinhead in \"The Bros\">\n<Todd David Lawhorne; co-stars; Shaquille O'Neal and Joey Fatone in \"The Bros\">\n<Todd David Lawhorne; theatre plays he starred in plays off and off-off Broadway in New York City; \"Twelfth Night\" at Lincoln Center, Laertes in Pineapple Project's production of \"Hamlet\">\n<Todd David Lawhorne; position; resident actor of the Children's Theatre at the New York Hall of Science>", 
    },
    # 11 - 15
    {
        "title": "1999 du Maurier Open \u2013 Men's Doubles",
        "text": "Martin Damm and Jim Grabb were the defending champions, but competed this year with different partners. Damm teamed up with Max Mirnyi and lost in second round to Ellis Ferreira and Rick Leach, while Grabb teamed up with Goran Ivani\u0161evi\u0107 and lost in quarterfinals also against Ferreira-Leach.",
        "triples": "<1999 du Maurier Open \u2013 Men's Doubles; participants; Damm, Jim Grabb, Max Mirnyi, Ellis Ferreira, Rick Leach, Goran Ivani\u0161evi\u0107>\n<1999 du Maurier Open \u2013 Men's Doubles; events; Damm teamed up with Max Mirnyi>\n<1999 du Maurier Open \u2013 Men's Doubles; events; Damm-Max Mirnyi team lost to Ellis Ferreira-Rick Leach team in second round>\n<1999 du Maurier Open \u2013 Men's Doubles; events; Grabb-Goran Ivani\u0161evi\u0107 lost to Ellis Ferreira-Rick Leach team in quarterfinals>"
    },
    {
        "title": "Kelie McIver",
        "text": "Kelie McIver is a Kansas-born actress and singer who has played classical stage roles such as Lady Macbeth and Nurse in \"Romeo & Juliet\" for Kingsmen Shakespeare Festival, Viola in \"Twelfth Night\" for both Nevada Shakespeare in the Park and Shakespeare at Play, Hecuba in \"The Trojan Women\", Kate in \"Taming of the Shrew\", Rosalind in \"As You Like It\", Doll Common in Mark Ringer's production of \"The Alchemist\" and as both Puck and Titania in separate productions of \"A Midsummer Night's Dream\". She has also appeared in roles in non-classical plays such as \"Ravenscroft\", \"Train of Thought\", \"The Matchmaker\", \"Madwoman of Chaillot\", and Jon Mullich's adaptation of \"A Servant of Two Masters\". McIver is a frequent performer at the \"Golden Raspberry Awards\" (RAZZIES) ceremony and has toured with the country music trio Mama Says! with Janet Fisher and Patti Shannon. She is a former president and long standing board member of the Midwest Entertainment Connection (MECONN), a nonprofit organization that connects the entertainment industries of Los Angeles and the Midwest. Her film appearances include the award-winning short film \"Trail End\" opposite Barry Corbin and the 2009 feature film \"Table for Three.\"",
        "triples": "<Kelie McIver; place of birth; Kansas>\n<Kelie McIver; occupation; actress and singer>\n<Kelie McIver; stage roles she played for Kingsmen Shakespeare Festival; Lady Macbeth and Nurse in \"Romeo & Juliet\">\n<Kelie McIver; stage roles she played for both Nevada Shakespeare in the Park and Shakespeare at Play; Viola in \"Twelfth Night\">\n<Kelie McIver; other stage roles she played in; Hecuba in \"The Trojan Women\", Kate in \"Taming of the Shrew\", Rosalind in \"As You Like It\", Doll Common in \"The Alchemist\", Puck and Titania in \"A Midsummer Night's Dream\">\n<Kelie McIver; non-classical plays she appeared in roles in; Ravenscroft, Train of Thought, The Matchmaker, Madwoman of Chaillot, Jon Mullich's adaptation of \"A Servant of Two Masters\">\n<Kelie McIver; is a frequent performer at; Golden Raspberry Awards (RAZZIES) ceremony>\n<Kelie McIver; group she toruted with; Mama Says!>\n<Kelie McIver; leadership role; former president and long standing board member of the Midwest Entertainment Connection (MECONN)>\n<Kelie McIver; film appearances; award-winning short film \"Trail End\" opposite Barry Corbin, the 2009 feature film \"Table for Three\">", 
    },
    {
        "title": "Hemant Batra",
        "text": "Hemant K. Batra (born 15 August 1967) is a Corporate, Business and Strategist commercial lawyer. He is the founder and Chairman of Kaden Boriss Global, a legal and business strategist organization of global law firms and offices. Kaden Boriss was founded in 2003 by international and business laws specialist lawyers Hemant Batra and Preeti Batra. The intellectual property rights (IPR) in the trade mark and copyright of legal brand Kaden Boriss (KB) vests with Hemant Batra Kaden Boriss was originally established as a partnership firm under the common law of the Indian partnership act but was later transformed into a newly set up regime of LLP. However, due to lack of clarity under the regulatory framework for lawyers and law firms, Kaden Boriss LLP reverted to its old structure under the older partnership law. It was also felt by the partners of Kaden Boriss that unless foreign direct investment was permitted in the Indian legal services sector, forming an LLP had hardly any added benefits. It also partnered with I-Inspire 2013, national conference for women leaders, aiming to be a confluence of ideas, a convergence of thoughts and celebration of the spirit of diversity and entrepreneurship. Hemant holds a position as the Secretary General of SAARCLAW (South Asian Association for Regional Co-operation in Law). SAARCLAW is a regional Apex body of SAARC (South Asian Association for Regional Cooperation). He is also the Chairperson of the Organizing Council of International Infrastructure & Construction Law Arbitration Moot (IICLAM) and Member of the Advisory Board of the Organisation for International Cooperation (OIC) based in New Jersey, USA. IICLAM is a joint initiative of Kaden Boriss, National University of Singapore (NUS) and Singapore International Arbitration Centre (SIAC), Singapore. He is recipient of prestigious Mahatma Gandhi Seva Medal with other awardees being the Dalai Lama, then President of India Shri K. R. Narayanan,UPA Chairperson & President of INC Smt Sonia Gandhi and Speaker Lok Sabha Smt Meira Kumar. Batra is author of speaking threads a collection of his thought provoking quotes. The most popular being - Think twice before saying `yes' and just once before saying `no'. Hemant Batra took over as the Chairman of the prestigious panel of jury for the grant of Aces Awards for Corporate Excellence and Sustainability in Asia.",
        "triples": "<Hemant Batra; date of birth; 15 August 1967>\n<Hemant Batra; occupation; Corporate, Business and Strategist commercial lawyer>\n<Hemant Batra; position within the organization; founder and Chairman of Kaden Boriss Global>\n<Hemant Batra; founded Kaden Boriss in 2003 with; Preeti Batra>\n<Hemant Batra; intellectual property; holds rights in the intellectual property rights (IPR) in the trade mark and copyright of legal brand Kaden Boriss (KB)>\n<Hemant Batra; the legal structure of his firm; partnership under Indian partnership act>\n<Hemant Batra; holds a position as; Secretary General of SAARCLAW (South Asian Association for Regional Co-operation in Law)>\n<Hemant Batra; collaboration with a conference for women leaders; partnered with I-Inspire 2013>\n<Hemant Batra; role; Chairperson of the Organizing Council of International Infrastructure & Construction Law Arbitration Moot (IICLAM)>\n<Hemant Batra; role; Member of the Advisory Board of the Organisation for International Cooperation (OIC)>\n<Hemant Batra; a prestigious award received; Mahatma Gandhi Seva Medal>\n<Hemant Batra; is author of; speaking threads>\n<Hemant Batra; the most popular quote; Think twice before saying `yes' and just once before saying `no'>\n<Hemant Batra; role; Chairman of the prestigious panel of jury for the grant of Aces Awards for Corporate Excellence and Sustainability in Asia>", 
    },
    {
        "title": "Gabriel (New-Gen)",
        "text": "John Gabriel is a fictional character, a superhero appearing in American comic books published by Marvel Comics. The character appears in the NEW-GEN comic books. Created by Chris Matonti, J.D. Matonti, and Julia Coppola, he first appeared in NEW-GEN #1 (2010). He is the founder and leader of the A.P.N.G., and the leading scientific mind in the field of nanotechnology on the world of New-Gen.",
        "triples": "<Gabriel (New-Gen); type; fictional character>\n<Gabriel (New-Gen); character genre; superhero>\n<Gabriel (New-Gen); appears in American comic books publised by; Marvel Comics>\n<Gabriel (New-Gen); appears in; NEW-GEN comic books>\n<Gabriel (New-Gen); creators; Chris Matonti, J.D. Matonti, and Julia Coppola>\n<Gabriel (New-Gen); first appearance in; NEW-GEN #1 (2010)>\n<Gabriel (New-Gen); role within the comic universe; founder and leader of the A.P.N.G., leading scientific mind in the field of nanotechnology>", 
    },
    {
        "title": "Fred Fleck",
        "text": "Fred Fleck (June 6, 1892 \u2013 November 9, 1961), also known as Fred A. Fleck, Frederick Fleck, or Freddie Fleck, was an American assistant director and production manager. Born in New York City on June 4, 1892, he broke into the film business as an assistant director on the 1928 silent film, \"The Riding Renegade\", directed by Wallace Fox. During his 30-year career, he would work on some notable films, with some notable directors. Some of those films include: the epic \"Hell's Angels\" (1930), directed by Howard Hughes; King Vidor's \"Bird of Paradise\" (1932); the Ginger Rogers' 1941 vehicle, Tom, Dick and Harry, directed by Garson Kanin; 1942's \"The Magnificent Ambersons\", directed by Orson Welles, and starring Joseph Cotten and Anne Baxter; \"Born to be Bad\" (1950), starring Joan Fontaine and Robert Ryan; and Josef von Sternberg's \"Jet Pilot\" (1957), starring John Wayne. Fleck was also one of the aerial cameramen on George Archainbaud's classic 1932 film, \"The Lost Squadron\".",
        "triples": "<Fred Fleck; also known as; Fred A. Fleck, Frederick Fleck, Freddie Fleck>\n<Fred Fleck; date of birth; June 6, 1892>\n<Fred Fleck; date of death; November 9, 1961>\n<Fred Fleck; nationality; American>\n<Fred Fleck; place of birth; New York City>\n<Fred Fleck; occupation; assistant director and production manager>\n<Fred Fleck; first film he worked on as an assistant director; The Riding Renegade>\n<Fred Fleck; notable films he worked on; Hell's Angels (1930, directed by Howard Hughes), Bird of Paradise (1932, directed by King Vidor), Tom, Dick and Harry (1941, directed by Garson Kanin), The Magnificent Ambersons (directed by Orson Welles), Born to be Bad (1950), Jet Pilot (1957, directed by Josef von Sternberg)>\n<Fred Fleck; role in a film; one of the aerial cameraman for The Lost Squadron>\n<Fred Fleck; career duration; 30-year career>",
    },
    # 16 - 20
    {
        "title": "Independent Hill, Virginia",
        "text": "Independent Hill is an unincorporated town in Prince William County, Virginia. It is located along State Route 234 at the intersection with Joplin Road. The only visible remaining businesses seem to be Samsky's Market (also a Citgo gas station) and Crosby's Crab Company. In early 2006, a realignment of 234 bypassed the town, leaving it on a side road. The greater Independent Hill area is defined by the Census Bureau as a census-designated place (CDP), with a population of 7,419 as of 2010.",
        "triples": "<Independent Hill, Virginia; administrative classification; unincorporated town>\n<Independent Hill, Virginia; county in which it is located; Prince William County, Virginia>\n<Independent Hill, Virginia; specific geographical location; located along State Route 234 at the intersection with Joplin Road>\n<Independent Hill, Virginia; remaining businesses; Samsky's Market (also a Citgo gas station) and Crosby's Crab Company>\n<Independent Hill, Virginia; events; a realignment of 234 bypassed the town in early 2006>\n<Independent Hill, Virginia; events; defined as census-designated place (CDP) by the Census Bureau>\n<Independent Hill, Virginia; population; 7,419 as of 2010>", 
    },
    {
        "title": "2000 Sports Racing World Cup",
        "text": "The 2000 Sports Racing World Cup was the fourth season of Sports Racing World Cup (later known as the FIA Sportscar Championship). It was a series for sportscar style prototypes broken into two classes based on power and weight, called SR and SRL (or SR2). It began on March 26, 2000 and ended November 26, 2000 after 10 races. The two American rounds were run in conjunction with Grand American Road Racing Championship, using similar SR rules.",
        "triples": "<2000 Sports Racing World Cup; season number; fourth season of Sports Racing World Cup>\n<2000 Sports Racing World Cup; later known as; FIA Sportscar Championship>\n<2000 Sports Racing World Cup; type of racing series; series for sportscar style prototypes>\n<2000 Sports Racing World Cup; different classes of cars based on power and weight; SR and SRL (or SR2)>\n<2000 Sports Racing World Cup; duration; began March 26, 2000 and ended November 26, 2000>\n<2000 Sports Racing World Cup; number of races; 10 races>\n<2000 Sports Racing World Cup; how the American rounds were organized; run in conjunction with Grand American Road Racing Championship>\n<2000 Sports Racing World Cup; type of rules applied during the American rounds; similar SR rules>",
    },
    {
        "title": "Game Dev Story",
        "text": "Game Dev Story is a simulation video game developed and published by Kairosoft for Microsoft Windows, iOS, and Android. It was released for Windows in April of 1997 , for iOS and Android on October 9, 2010, and for Windows Phone on July 6, 2015. The game follows a player-controlled video game company and its attempts to expand into a sales powerhouse over time. As a simulation, the game and the direction of the company is controlled by the player, following a parallel timeline of the video game industry and its history. The game was released to positive reviews, with many reviewers focusing on \"Game Dev Story\"' s addictive aspects and its witty references to video game pop culture.",
        "triples": "<Game Dev Story; genre of game; simulation video game>\n<Game Dev Story; company that developed and published the game; Kairosoft>\n<Game Dev Story; platform; Microsoft Windows, iOS, Android, Windows Phone>\n<Game Dev Story; release date; Windows in April 1997, iOS and Android on October 9, 2010, Windows Phone on July 6, 2015>\n<Game Dev Story; main activity of the game; players controlled a video game company and attempt to expand it into a sales powerhouse over time>\n<Game Dev Story; how the game was received by critics; positive reviews>\n<Game Dev Story; aspects of the game that were particularly noted by reviewers; addictive aspects and its witty references to video game pop culture>", 
    },
    {
        "title": "Andrew Szanton",
        "text": "Andrew Szanton (born in Washington, D.C. in 1963) is an American collaborative memoirist. During his career he has worked with a wide range of subjects including civil rights pioneer Charles Evers, Nobel Prize winning physicist Eugene Wigner, former co-chairman of Goldman Sachs John Whitehead, former United States Senator Edward Brooke, founding director of Xerox PARC George Pake, eminent surgeon Dr. Charles Epps, head of the Missouri Botanical Garden Peter Raven, and former Boston mayor Raymond Flynn.",
        "triples": "<Andrew Szanton; place of birth; Washington, D.C.>\n<Andrew Szanton; year of birth; 1963>\n<Andrew Szanton; nationality; American>\n<Andrew Szanton; occupation; collaborative memoirist>\n<Andrew Szanton; individuals he has worked with; Charles Evers (civil rights pioneer), Eugene Wigner (Nobel Prize winning physicist), John Whitehead (former co-chairman of Goldman Sachs), Edward Brooke (former United States Senator), George Pake (founding director of Xerox PARC), Charles Epps (eminent surgeon), Peter Raven (head of the Missouri Botanical Garden), Raymond Flynn (former Boston mayor)>", 
    },
    {
        "title": "Aaron A. Brooks",
        "text": "Aaron A. Brooks, also known as, Aaron Kinsley-Brooks (born January 24, 1964, San Francisco, California) is an American rock musician, drummer, producer and composer. He co-founded The Little Death with Moby, Laura Dawn and Daron Murphy. He is a founding member of the American alternative rock band, The Mars Bonfire. Aaron also plays or has played drums for the electronic pop band Leisure Cruise; Grammy nominated electro-pop chanteuse Angela McCluskey (of T\u00e9l\u00e9popmusik and Wild Colonials); Grammy award-winning producer/songwriter Mark Hudson; Emmy award-winning actress and singer Jackie Cruz; Grammy award-winning artist Moby; Singer/songwriter and progressive political activist Laura Dawn; Grammy award-winning bassist/songwriter and rock musician Duff McKagen of Guns N' Roses; Circle of Soul; Erin Evermore; Grammy award-winning pianist and songwriter A.J. Croce; Grammy winning singer/songwriter Lana Del Ray; Writer, radio host, progressive political comic and guitarist/singer Jamie Kilstein and his band The Agenda; Model/actress/singer/songwriter Heidi Merrill; And NY based rock singer Carleigh Jade.",
        "triples": "<Aaron A. Brooks; also known as; Aaron Kinsley-Brooks>\n<Aaron A. Brooks; date of birth; January 24, 1964>\n<Aaron A. Brooks; place of birth; San Francisco, California>\n<Aaron A. Brooks; nationality; American>\n<Aaron A. Brooks; occupation; rock musician, drummer, producer, composer>\n<Aaron A. Brooks; co-founded; The Little Death with Moby, Laura Dawn and Daron Murphy>\n<Aaron A. Brooks; the American alternative rock band he was a founding member of; The Mars Bonfire>\n<Aaron A. Brooks; artists he plays or has played drums for; Leisure Cruise (electronic pop band), Angela McCluskey (Grammy nominated electro-pop chanteuse), Mark Hudson (Grammy award-winning producer/songwriter), Jackie Cruz (Emmy award-winning actress and singer), Moby (Grammy award-winning artist), Laura Dawn (Singer/songwriter and progressive political activist), Duff McKagen (Grammy award-winning bassist/songwriter and rock musician), A.J. Croce (Grammy award-winning pianist and songwriter), Lana Del Ray (Grammy winning singer/songwriter), Jamie Kilstein (Writer, radio host, progressive political comic and guitarist/singer), Heidi Merrill (Model/actress/singer/songwriter), Carleigh Jade (NY based rock singer)>", 
    },
    # 21 - 25 
    {
        "title": "Inaindha Kaigal",
        "text": "Inaindha Kaigal (English: Conjoined Hands ) is a 1990 Indian Tamil film, directed by N. K. Vishwanathan. The film features C. Arunpandian, Ramki, Nirosha and Sindhu in lead roles, with Nassar, Senthil, Srividya, Murali Kumar and Prabhakaran playing supporting roles. The film, produced by Aabavanan who also wrote the script and lyrics, had musical score by Gyan Varma and was released on 2 August 1990. The film is a blockbuster in the year 1990 and became a successful venture. The film has been dubbed in Hindi as \"Aakhri Sangam\" and in Telugu as Sahasa Ghattam.", 
        "triples": "<Inaindha Kaigal; English translation; Conjoined Hands>\n<Inaindha Kaigal; the year when the film was released; 1990>\n<Inaindha Kaigal; genre of the film; Indian Tamil film>\n<Inaindha Kaigal; director of the film; N. K. Vishwanathan>\n<Inaindha Kaigal; lead actors; C. Arunpandian, Ramki, Nirosha, Sindhu>\n<Inaindha Kaigal; supporting actors; Nassar, Senthil, Srividya, Murali Kumar, Prabhakaran>\n<Inaindha Kaigal; individual who produced and also wrote the script and lyrics for the film; Aabavanan>\n<Inaindha Kaigal; composer of the film's musical score; Gyan Varma>\n<Inaindha Kaigal; release date of the film; 2 August 1990>\n<Inaindha Kaigal; the status of the film in its release year; blockbuster in 1990 and became a successful venture>\n<Inaindha Kaigal; Hindi version name of the film; Aakhri Sangam>\n<Inaindha Kaigal; Telugu version name of the film; Sahasa Ghattam>", 
    },
    {
        "title": "Wormburner",
        "text": "Wormburner is an indie rock band based in Brooklyn, New York. Their music has been categorized as college rock. The band has five members, and is led by Steve \"Hank\" Henry, who is the band's singer, guitarist, and songwriter. Henry graduated from Colgate University in 1993. Their debut album, \"A Hero's Welcome\", was released in 2006 and produced by David Lowery of Cracker. The band wrote and recorded the album's 12 songs at Lowery's studio in Richmond, Virginia. These songs' power-pop sound, along with a series of live shows by the band, led to the band and album becoming increasingly popular. The band released its second album, \"Placed by the Gideons\", in 2010 on the label Wax Off, which is partly run by WSUM host DJ Renton. In 2012, the band was interviewed for MTV's series 120 Minutes. Their third album, \"Pleasant Living in Planned Communities\", was released on Dive Records in September 2014. Prior to its release, a song from the album, \"Somewhere Else to Be\", was premiered by Brooklyn Magazine. Robert Christgau gave \"Pleasant Living in Planned Communities\" an A- grade, writing that on the album, \"Hank Henry doesn't swallow a word as he shouts his tuneful tales into the void, and unlike Craig Finn [of the Hold Steady], he doesn't specialize in or even much notice the human dregs and heroes of the alt-rock scene.\"",
        "triples": "<Wormburner; genre of the band; indie rock, college rock>\n<Wormburner; location where the band is based; Brooklyn, New York>\n<Wormburner; band leader; Steve \"Hank\" Henry>\n<Wormburner; roles of Steve Henry in the band; singer, guitarist, songwriter>\n<Wormburner; education of the band leader; Henry graduated from Colgate University in 1993>\n<Wormburner; debut album; A Hero's Welcome>\n<Wormburner; producer of the debut album of the band; David Lowery>\n<Wormburner; the release year of the debut album of the band; 2006>\n<Wormburner; location of debut album recording; Lowery's studio in Richmond, Virginia>\n<Wormburner; number of songs in the debut album of the band; 12>\n<Wormburner; second album; Placed by the Gideons>\n<Wormburner; release year of the second album of the band; 2010>\n<Wormburner; record label for the second album of the band; Wax Off>\n<Wormburner; events; the band was interviewed for MTV's series 120 Minutes in 2012>\n<Wormburner; third album; Pleasant Living in Planned Communities>\n<Wormburner; record label for the third album of the band; Dive Records>\n<Wormburner; release date of the third album of the band; September 2014>\n<Wormburner; songs in the third album of the band; Somewhere Else to Be>\n<Wormburner; review of the third album of the band by Robert Christgau; A- grade>",
    },
    {
        "title": "Wonky (album)",
        "text": "Wonky is the eight studio album by Orbital, released on their own ACP label (via Warner Music Group/Alternative Distribution Alliance) in the UK on 2 April 2012, and exclusively through iTunes in the USA and Canada on 17 April 2012. The album is their first since the \"Blue Album\" in 2004 and the first since they reformed in 2008. It features vocals from Zola Jesus and Lady Leshurr. The album was taken off of Spotify and iTunes in the United States for unknown reasons. There are some songs you cannot find at all in their original versions, like Beelzedub or Distractions.",
        "triples": "<Wonky (album); band of the album; Orbital>\n<Wonky (album); album number of the band; eighth studio album>\n<Wonky (album); record label; ACP label (via Warner Music Group/Alternative Distribution Alliance)>\n<Wonky (album); release date and place; 2 April 2012 in the UK>\n<Wonky (album); release date and place; 17 April 2012 through iTunes in the USA and Canada>\n<Wonky (album); status; first album of the band since the \"Blue Album\" in 2004>\n<Wonky (album); status; first album of the band since its reformation in 2008>\n<Wonky (album); featuring; vocals from Zola Jesus and Lady Leshurr>\n<Wonky (album); availability issue; taken off Spotify and iTunes in the United States>\n<Wonky (album); songs unavailable in their original versions; Beelzedub, Distractions>", 
    },
    {
        "title": "United States v. Silk",
        "text": "United States v. Silk, 331 U.S. 704 (1947) , was a United States Supreme Court case regarding US labor law. The case concerned the scope of protection for employees under the Social Security Act 1935.",
        "triples": "<United States v. Silk; formal citation of the case; 331 U.S. 704 (1947)>\n<United States v. Silk; year the case was decided; 1947>\n<United States v. Silk; court that adjudicated the case; United States Supreme Court>\n<United States v. Silk; legal focus; US labor law>\n<United States v. Silk; issue; scope of protection for employees under the Social Security Act 1935>", 
    },
    {
        "title": "A Birder's Guide to Everything",
        "text": "A Birder's Guide to Everything is an independent film starring Kodi Smit-McPhee, Alex Wolff, Michael Chen, Katie Chang, James Le Gros, Daniela Lavender and Sir Ben Kingsley. It was written by Rob Meyer and Luke Matheny and directed by Rob Meyer. The film had its world premiere at the Tribeca Film Festival on April 21, 2013. and was released in a limited release and through video on demand on March 21, 2014 by Screen Media Films and Focus Features.",
        "triples": "<A Birder's Guide to Everything; genre of film; independent film>\n<A Birder's Guide to Everything; starring; Kodi Smit-McPhee, Alex Wolff, Michael Chen, Katie Chang, James Le Gros, Daniela Lavender, Sir Ben Kingsley>\n<A Birder's Guide to Everything; writers of the film; Rob Meyer and Luke Matheny>\n<A Birder's Guide to Everything; director of the film; Rob Meyer>\n<A Birder's Guide to Everything; events; had its world premiere at the Tribeca Film Festival on April 21, 2013>\n<A Birder's Guide to Everything; release date of the film; March 21, 2014>\n<A Birder's Guide to Everything; companies that distributed the film; Screen Media Films and Focus Features>",
    },
    # 26 - 30 
    {
        "title": "Marissa Academy",
        "text": "The Marissa Academy is a historic school building located at 610 S. Main St. in Marissa, Illinois. The building was built in 1891 for the Marissa Academy, a college preparatory academy which had graduated its first class two years prior. The private school was the first college preparatory school in the area. Graduating students at the academy could enroll at Monmouth College without taking a qualifying examination under a special arrangement. In 1900, the academy closed after a public high school opened in Marissa. The building has since been used as a meeting hall for community groups and as additional space for Marissa's elementary school. It is now the headquarters of the Marissa Historical and Genealogical Society.",
        "triples": "<Marissa Academy; type; historic private school building>\n<Marissa Academy; location; 610 S. Main St., Marissa, Illinois>\n<Marissa Academy; construction year; 1891>\n<Marissa Academy; initial function of the building; college preparatory academy>\n<Marissa Academy; notable attribute of the school; first college preparatory school in the area>\n<Marissa Academy; special educational arrangement; gradudate students could enroll at Monmouth College without qualifying exam>\n<Marissa Academy; events; closed after a public high school opened in Marissa in 1900>\n<Marissa Academy; later functions of the building after the academy closed; meeting hall for community groups, additional space for Marissa's elementary school>\n<Marissa Academy; present function of the building; headquarters of the Marissa Historical and Genealogical Society>",
    },
    {
        "title": "2015 Barbados Premier Division",
        "text": "The 2015 Barbados Premier Division (officially the Digicel Premiere League for sponsorship reasons) was the 69th season of the highest tier of football in Barbados. Barbados Defense Force won their final six matches to hold off Rendezvous FC for their third consecutive league title and fifth overall. With BDF having already completed their schedule, Rendezvous FC needed to make up 11 goals in goal differential with a win on the final day of the season to pull even with BDF, but managed only a 2-1 victory over Weymouth Wales. The season began on February 8 and concluded on July 23.",
        "triples": "<2015 Barbados Premier Division; official name; Digicel Premiere League>\n<2015 Barbados Premier Division; season number; 69th season>\n<2015 Barbados Premier Division; tier; highest tier of football in Barbados>\n<2015 Barbados Premier Division; events; Barbados Defense Force won their final six matches to hold off Rendezvous FC for their third consecutive league title and fifth overall>\n<2015 Barbados Premier Division; events; With BDF having already completed their schedule, Rendezvous FC needed to make up 11 goals in goal differential with a win on the final day of the season to pull even with BDF, but managed only a 2-1 victory over Weymouth Wales>\n<2015 Barbados Premier Division; season duration; began on February 8 and ended on July 23>", 
    },
    {
        "title": "2014 WKU Hilltoppers football team",
        "text": "The 2014 Western Kentucky Hilltoppers football team represented Western Kentucky University (WKU) in the 2014 NCAA Division I FBS football season. They were led by first- year head coach Jeff Brohm and played their home games at Houchens Industries\u2013L. T. Smith Stadium. This was the team's first year as a Conference USA member and playing in the East Division. They finished the season 8\u20135, 4\u20134 in C-USA play to finish in a three way tie for third place in the East Division. They were invited to the Bahamas Bowl where they defeated Central Michigan.",
        "triples": "<2014 WKU Hilltoppers football team; university the team represented; Western Kentucky University (WKU)>\n<2014 WKU Hilltoppers football team; participated in; 2014 NCAA Division I FBS football season>\n<2014 WKU Hilltoppers football team; head coach; Jeff Brohm>\n<2014 WKU Hilltoppers football team; location where home games of the team were played; Houchens Industries\u2013L. T. Smith Stadium>\n<2014 WKU Hilltoppers football team; notable features; first year as a Conference USA member and playing in the East Division>\n<2014 WKU Hilltoppers football team; record of the team in the season of C-USA; 8\u20135, 4\u20134>\n<2014 WKU Hilltoppers football team; conference standing; finish in a three way tied for third place in East Division>\n<2014 WKU Hilltoppers football team; postseason; invited to the Bahamas Bowl>\n<2014 WKU Hilltoppers football team; Bahamas Bowl outcome; defeated Central Michigan>", 
    },
    {
        "title": "The Duo",
        "text": "The Duo () is a 2011 South Korean historical drama series, starring Chun Jung-myung, Lee Sang-yoon, Han Ji-hye and Seo Hyun-jin. It aired on MBC from February 7 to May 24, 2011 on Mondays and Tuesdays at 21:55 for 32 episodes.",
        "triples": "<The Duo; country of origin; South Korea>\n<The Duo; genre; historical drama series>\n<The Duo; starring; Chun Jung-myung, Lee Sang-yoon, Han Ji-hye, Seo Hyun-jin>\n<The Duo; television network that aired the series; MBC>\n<The Duo; air days and time; from February 7 to May 24, 2011 on Mondays and Tuesdays at 21:55>\n<The Duo; number of episodes; 32 episodes>", 
    },
    {
        "title": "Ex Mach Tina",
        "text": "\"Ex Mach Tina\" is the 8th episode of the seventh season of the American animated comedy series \"Bob's Burgers\" and the 115th episode overall. It was written by Greg Thompson and directed by Brian Loschiavo. Its guest stars are David Herman as Mr.\u00a0Frond and as Mr.\u00a0Branca, Robert Smigel as the school's night security guard, Samantha Bee as school nurse Liz, Jenny Slate as Tammy Larsen and Bobby Tisdale as Zeke. It originally aired in the US on FOX Network at January 8, 2017. In this episode Tina hurts her ankle and uses a telecommunication robot for school, so she can stay at home. Jimmy Jr. develops a relationship to the robot version of Tina. Meanwhile Bob buys a banjo and waits for a good moment to play it.",
        "triples": "<Ex Mach Tina; type; an episode of the seventh season of the American animated comedy series \"Bob's Burgers\">\n<Ex Mach Tina; episode number in season; 8th episode>\n<Ex Mach Tina; overall episode number; 115th episode>\n<Ex Mach Tina; writer of the eposide; Greg Thompson>\n<Ex Mach Tina; director of the eposide; Brian Loschiavo>\n<Ex Mach Tina; guest stars; David Herman as Mr.\u00a0Frond and as Mr.\u00a0Branca, Robert Smigel as the school's night security guard, Samantha Bee as school nurse Liz, Jenny Slate as Tammy Larsen and Bobby Tisdale as Zeke>\n<Ex Mach Tina; network that aired the eposide; FOX Network>\n<Ex Mach Tina; air date; January 8, 2017>\n<Ex Mach Tina; key plot elements; Tina hurts her ankle and uses telecommunication robot, Jimmy Jr. develops relationship with robot, Bob buys banjo>", 
    },
    # 30 - 35 
    {
        "title": "Brett Polegato",
        "text": "Brett Polegato (born 1968 in Niagara Falls, Ontario, Canada) is an operatic baritone. In 1999 he made his Lyric Opera of Chicago debut as Peter Niles in Levy's \"Mourning Becomes Electra\" followed by his La Scala debut in 2000 as Ned Keene in Britten's \"Peter Grimes\". He is particularly known for his interpretation of the title role in Debussy's \"Pell\u00e9as et M\u00e9lisande\" which he has performed with many companies including the Bavarian State Opera, Op\u00e9ra National de Paris, Oper Leipzig, and Op\u00e9ra National du Rhin among others. Other European appearances include Ubalde in Gluck's \"Armide\" at Op\u00e9ra de Nice, the title role in Monteverdi's \"Orfeo\" at Op\u00e9ra d'Avignon, and Fr\u00e8re L\u00e8on in Messaien's \"Saint Fran\u00e7ois d'Assise\" at Op\u00e9ra National de Paris. He has sung numerous roles with Flanders Opera, including Guglielmo in Mozart's \"Cos\u00ec fan tutte\", Albert in Massenet's \"Werther\", and the Steward in Jonathan Dove's \"Flight\". In his native Canada, Polegato has sung Papageno in Mozart's \"Die Zauberfl\u00f6te\", Figaro in Rossini's \"Il barbiere di Siviglia\", and Zurga in Bizet's \"Les p\u00eacheurs de perles\" with Vancouver Opera. In the United States, he has sung with New York City Opera, Houston Grand Opera, and Michigan Opera Theatre as well as making many concert appearances and recordings with American orchestras. He made his Seattle Opera debut in 2005 as Henry Miles in Jake Heggie's \"The End of the Affair\" and returned to the company in 2007 as Orestes in Gluck's \"Iphigenia in Tauris\".",
        "triples": "<Brett Polegato; year of birth; 1968>\n<Brett Polegato; place of birth; Niagara Falls, Ontario, Canada>\n<Brett Polegato; occupation; operatic baritone>\n<Brett Polegato; debut in Lyric Opera of Chicago in 1999; played Peter Niles in Levy's \"Mourning Becomes Electra\">\n<Brett Polegato; debut in La Scala in 2000; played Ned Keene in Britten's \"Peter Grimes\">\n<Brett Polegato; a role he is particularly known for; title role in Debussy's \"Pelléas et Mélisande\">\n<Brett Polegato; opera companies he has performed with; Bavarian State Opera, Op\u00e9ra National de Paris, Oper Leipzig, and Op\u00e9ra National du Rhin among others>\n<Brett Polegato; European appearances; Ubalde in Gluck's \"Armide\" at Op\u00e9ra de Nice, the title role in Monteverdi's \"Orfeo\" at Op\u00e9ra d'Avignon, and Fr\u00e8re L\u00e8on in Messaien's \"Saint Fran\u00e7ois d'Assise\" at Op\u00e9ra National de Paris>\n<Brett Polegato; roles he has sung with Flanders Opera; Guglielmo in Mozart's \"Cos\u00ec fan tutte\", Albert in Massenet's \"Werther\", and the Steward in Jonathan Dove's \"Flight\">\n<Brett Polegato; roles he has sung in Canada; Papageno in Mozart's \"Die Zauberfl\u00f6te\", Figaro in Rossini's \"Il barbiere di Siviglia\", and Zurga in Bizet's \"Les p\u00eacheurs de perles\" with Vancouver Opera>\n<Brett Polegato; Opera and bands he has cooperated with in the United States; New York City Opera, Houston Grand Opera, and Michigan Opera Theatre, American orchestras>\n<Brett Polegato; events; Seattle Opera debut in 2005 as Henry Miles in Jake Heggie's \"The End of the Affair\">\n<Brett Polegato; events; returned to the Seattle Opera in 2007 as Orestes in Gluck's \"Iphigenia in Tauris\">", 
    },
    {
        "title": "Julie O'Neill",
        "text": "Julie O'Neill is an English fiction author. She was born in Yorkshire in 1971. O'Neill attended Edinburgh University before embarking on a career in glamour modelling. In her twenties and early thirties O'Neill travelled the world, and spent time living in France, Morocco, Vietnam, Malaysia, Spain and Portugal. She worked as, amongst other things, a shop dresser, journalist, burlesque dancer, dominatrix, rubber bouncer, security service operative, children's party entertainer, hypnotherapist, Hazelnut sorter and night club DJ. Before returning to England she spent three years travelling through the Far East on an elephant called Bolabesar.",
        "triples": "<Julie O'Neill; nationality; English>\n<Julie O'Neill; occupation; fiction author>\n<Julie O'Neill; place of birth; Yorkshire>\n<Julie O'Neill; year of birth; 1971>\n<Julie O'Neill; education; attended Edinburgh University>\n<Julie O'Neill; initial occupation; glamour modelling>\n<Julie O'Neill; countries she has lived in; France, Morocco, Vietnam, Malaysia, Spain, Portugal>\n<Julie O'Neill; occupations she held; shop dresser, journalist, burlesque dancer, dominatrix, rubber bouncer, security service operative, children's party entertainer, hypnotherapist, Hazelnut sorter, night club DJ>\n<Julie O'Neill; events; spent three years travelling through the Far East on an elephant called Bolabesar before returning to England>", 
    },
    {
        "title": "Jermain Mackey",
        "text": "Jermain \"Choo Choo\" Mackey ( (1979--) 27 1979 (age\u00a037 ) ) born in Nassau is a Bahamian professional middle/super middle/light heavyweight boxer of the 2000s and 2010s who won the Bahamas super middleweight title, World Boxing Council (WBC) Caribbean Boxing Federation (CABOFE) super middleweight title, World Boxing Association (WBA) Fedecaribe super middleweight title, Commonwealth super middleweight title, and was a challenger for the World Boxing Organization (WBO) North American Boxing Organization (NABO) super middleweight title against Jean Pascal, WBC International super middleweight title against Adonis Stevenson, and World Boxing Association Fedelatin super middleweight title against Kirt Sinnette, his professional fighting weight varied from 160+3/4 lb , i.e. welterweight to 170 lb , i.e. light heavyweight. He represented the Bahamas at the 2002 Commonwealth Games.",
        "triples": "<Jermain Mackey; nickname; Choo Choo>\n<Jermain Mackey; year of birth; 1979>\n<Jermain Mackey; age; 37>\n<Jermain Mackey; place of birth; Nassau>\n<Jermain Mackey; nationality; Bahamian>\n<Jermain Mackey; occupation; professional middle/super middle/light heavyweight boxer>\n<Jermain Mackey; the decades during which he was active in boxing; 2000s and 2010s>\n<Jermain Mackey; titles won; Bahamas super middleweight, WBC CABOFE super middleweight, WBA Fedecaribe super middleweight, Commonwealth super middleweight>\n<Jermain Mackey; titles he challenged for and against whom; World Boxing Organization (WBO) North American Boxing Organization (NABO) super middleweight against Jean Pascal, WBC International super middleweight against Adonis Stevenson, WBA Fedelatin super middleweight against Kirt Sinnette>\n<Jermain Mackey; fighting weight categories; from 160+3/4 lb , i.e. welterweight to 170 lb , i.e. light heavyweight>\n<Jermain Mackey; represented; Bahamas at 2002 Commonwealth Games>", 
    },
    {
        "title": "Champion Air",
        "text": "Champion Air was an airline based in Bloomington, Minnesota, USA. It operated general charter services to sports teams, vacation wholesalers and government agencies. It also offered limited scheduled service. Its main base was Minneapolis-Saint Paul International Airport, with hubs at Denver International Airport, Dallas-Fort Worth International Airport, Detroit Metropolitan Wayne County Airport, McCarran International Airport in Las Vegas, Lambert-St. Louis International Airport, and Will Rogers World Airport in Oklahoma City. The airline ceased all operations on May 31, 2008. Until its shutdown, the airline was a prime contractor for the Justice Prisoner and Alien Transportation System.",
        "triples": "<Champion Air; type; airline>\n<Champion Air; location; Bloomington, Minnesota, USA>\n<Champion Air; type of services offered by the airline; general charter services>\n<Champion Air; clients served by the airline; sports teams, vacation wholesalers, government agencies>\n<Champion Air; main base; Minneapolis-Saint Paul International Airport>\n<Champion Air; hubs; Denver International Airport, Dallas-Fort Worth International Airport, Detroit Metropolitan Wayne County Airport, McCarran International Airport, Lambert-St. Louis International Airport, Will Rogers World Airport>\n<Champion Air; the date when the ariline ceased all operations; May 31, 2008>\n<Champion Air; contract role until its shutdown; prime contractor for the Justice Prisoner and Alien Transportation System>",
    },
    {
        "title": "LAS Magazine",
        "text": "LAS Magazine, also known as Lost At Sea or LostAtSea.net, is a daily online magazine founded in 1998 by Eric J Herboth. An online social group for the magazine list it in the \"Entertainment & Arts - Online Media\" category with a description of \"Art. Bike. Music. Media. Literature. Photography. Travel. Comics. Festivals. Sports? Yeah, a bit of that, too. Updated whenever, forever, since 1998.\" The magazine includes writing and photography contributions from Canada, Mexico, the United States, England, Scotland, Spain, Portugal, Germany, Switzerland, France, South Africa, Australia, Japan, New Zealand and Washington DC, but the publication maintains no fixed office.",
        "triples": "<LAS Magazine; also known as; Lost At Sea or LostAtSea.net>\n<LAS Magazine; type; daily online magazine>\n<LAS Magazine; founder; Eric J Herboth>\n<LAS Magazine; founding year; 1998>\n<LAS Magazine; category under which the magazine is listed by an online social group; Entertainment & Arts - Online Media>\n<LAS Magazine; topics convered by the magazine; Art. Bike. Music. Media. Literature. Photography. Travel. Comics. Festivals. Sports>\n<LAS Magazine; update frequency; Updated whenever, forever, since 1998>\n<LAS Magazine; countries and regions from which the magazine receives contributions; Canada, Mexico, United States, England, Scotland, Spain, Portugal, Germany, Switzerland, France, South Africa, Australia, Japan, New Zealand, Washington DC>\n<LAS Magazine; office status; no fixed office>", 
    },
    # 36 - 40 
    {
        "title": "David Kelly (association footballer)",
        "text": "David Thomas Kelly (born 25 November 1965), also known by the nickname Ned Kelly, is a former Republic of Ireland international footballer who now works as joint-caretaker-manager at EFL League Two club Port Vale, alongside Chris Morgan. He scored nine goals in 26 international games for the Republic of Ireland, and was a squad member for UEFA Euro 1988, the 1990 FIFA World Cup, and the 1994 FIFA World Cup. A forward, he scored a total of 250 goals in 744 league and cup appearances in a 19-year career in professional football.",
        "triples": "<David Kelly (association footballer); full name; David Thomas Kelly>\n<David Kelly (association footballer); nickname; Ned Kelly>\n<David Kelly (association footballer); date of birth; 25 November 1965>\n<David Kelly (association footballer); nationality; Republic of Ireland>\n<David Kelly (association footballer); occupation; joint-caretaker-manager at EFL League Two club Port Vale>\n<David Kelly (association footballer); colleague at EFL League Two club Port Vale; Chris Morgan>\n<David Kelly (association footballer); scoring record in 26 international games for the Republic of Ireland; nine goals>\n<David Kelly (association footballer); squad member for; UEFA Euro 1988, the 1990 FIFA World Cup, and the 1994 FIFA World Cup>\n<David Kelly (association footballer); scoring achievements throughout his career; scored a total of 250 goals in 744 league and cup appearances>\n<David Kelly (association footballer); career length; 19-year career in professional football>",
    },
    {
        "title": "Bloquera",
        "text": "Bloquera is an EP created by Maanumental, Newman, Sir Kado, Superbrush 427 (Giant Panda) and Thes One (People Under The Stairs). The group decided to take a spur of the moment road trip to Mexico as an ultimate road trip. The album was a result of a two-week road trip to Muleg\u00e9, Baja California Sur, Mexico which was the inspiration for the album.",
        "triples": "<Bloquera; type; EP (Extended Play)>\n<Bloquera; creators; Maanumental, Newman, Sir Kado, Superbrush 427 (Giant Panda) and Thes One (People Under The Stairs)>\n<Bloquera; event that inspired the creation of the album; a two-week road trip to Muleg\u00e9, Baja California Sur, Mexico>",
    },
    {
        "title": "WonderWorks",
        "text": "WonderWorks was an anthology series which ran from 1984 to 1992 co-produced by The Walt Disney Company and PBS that made short, made for TV movies out of acclaimed children's books. They included adaptations of \"Anne of Green Gables\", \"Bridge to Terabithia\", \"All Summer in a Day\", \"Jacob Have I Loved\", \"The Box of Delights\", \"The Chronicles of Narnia\" series, \"Miracle at Moreaux\", \"The Hoboken Chicken Emergency\" (starring Peter Billingsley), \"Odile & Yvette at the Edge of the World\" (scored by Blake Leyh), \"How to Be a Perfect Person in Just Three Days!\" (by Stephen Manes), \"Gryphon\" (produced by Manuel Arce and Carl Haber, starring Amanda Plummer), \"A Little Princess\", \"A Girl of the Limberlost\", \"Sweet 15\", \"A Waltz Through the Hills\", \"The Canterville Ghost\", \"Frog,\" \"The Haunting of Barney Palmer\", \"Caddie Woodlawn\", \"The House of Dies Drear\", and \"The Boy Who Loved Trolls\". It also co-produced the Australian \"Clowning Around\" series.",
        "triples": "<WonderWorks; type; anthology series>\n<WonderWorks; years during which the series was active; 1984 to 1992>\n<WonderWorks; co-producers; The Walt Disney Company and PBS>\n<WonderWorks; type of content produced for the series; made for TV movies out of acclaimed children's books>\n<WonderWorks; children's books that were adapted into TV movies for the series; Anne of Green Gables, Bridge to Terabithia, All Summer in a Day, Jacob Have I Loved, The Box of Delights, The Chronicles of Narnia, Miracle at Moreaux, The Hoboken Chicken Emergency, Odile & Yvette at the Edge of the World, How to Be a Perfect Person in Just Three Days!, Gryphon, A Little Princess, A Girl of the Limberlost, Sweet 15, A Waltz Through the Hills, The Canterville Ghost, Frog, The Haunting of Barney Palmer, Caddie Woodlawn, The House of Dies Drear, The Boy Who Loved Trolls>\n<WonderWorks; international collaboration; co-produced \"Clowning Around\" series in Australia>",
    },
    {
        "title": "Kyle Mackey",
        "text": "Kyle Erickson Mackey (born March 2, 1962) is an American Football coach and former American football quarterback who played for the New York Jets, St. Louis Cardinals, Philadelphia Eagles, and the Miami Dolphins of the National Football League. He was also an Arena Football League player, who played quarterback for the Albany Firebirds and the Fort Worth Cavalry. He played college football at Texas A&M University-Commerce from 1980-1983 where he was an All-American and led the Lions to the 1983 Lone Star Conference Championship. His father was Dee Mackey, a former tight end for the New York Jets.",
        "triples": "<Kyle Mackey; full name; Kyle Erickson Mackey>\n<Kyle Mackey; date of birth; March 2, 1962>\n<Kyle Mackey; nationality; American>\n<Kyle Mackey; occupation; Football coach and former quarterback>\n<Kyle Mackey; National Football League he played for; New York Jets, St. Louis Cardinals, Philadelphia Eagles, Miami Dolphins>\n<Kyle Mackey; Arena Football League teams he played quarterback for; Albany Firebirds, Fort Worth Cavalry>\n<Kyle Mackey; events; played college football at Texas A&M University-Commerce from 1980-1983 where he was an All-American and led the Lions to the 1983 Lone Star Conference Championship>\n<Kyle Mackey; father; Dee Mackey>", 
    },
    {
        "title": "Bihou",
        "text": "Bihou (), or Bei Hou or Pei Hou is a village just west of Taicheng in Taishan City in the Guangdong Province of southern China, and is located at latitude 22\u00b0 15' 09.22\" N and longitude 112\u00b0 46' 01.12\" E, 11 meters above sea level off the Cinnamon Stream Road (). Bi Hou was founded in the 18th century by Tan Gong Chang (), one of the many descendants of the viscounts of the feudal State of Tan (1046BC-684BC) in present-day Shandong Province.",
        "triples": "<Bihou; also known as; Bei Hou, Pei Hou>\n<Bihou; type; village>\n<Bihou; location; west of Taicheng in Taishan City in the Guangdong Province of southern China>\n<Bihou; geographic coordinates; latitude 22\u00b0 15' 09.22\" N and longitude 112\u00b0 46' 01.12\" E>\n<Bihou; elevation; 11 meters above sea level>\n<Bihou; road or access route to the village; Cinnamon Stream Road>\n<Bihou; the century when the village was founded; 18th century>\n<Bihou; founder; Tan Gong Chang>\n<Bihou; historical background of the founder of the village; founded by one of the many descendants of the viscounts of the feudal State of Tan (1046BC-684BC) in present-day Shandong Province>", 
    },
    # 41 - 45 
    {
        "title": "AZFinText",
        "text": "Arizona Financial Text System (AZFinText) is a quantitative textual financial prediction system written by Robert P. Schumaker of University of Texas at Tyler and Hsinchun Chen of the University of Arizona. This system differs from other quants because it uses financial text as one of its key means of predicting stock price movement. This reduces the information lag-time problem evident in many similar systems where new information must be transcribed (e.g., such as losing a costly court battle or having a product recall), before the quant can react appropriately. AZFinText overcomes these limitations by utilizing the terms used in financial news articles to predict future stock prices twenty minutes after the news article has been released. It is believed that certain article terms can move stocks more than others. Terms such as \"factory exploded\" or \"workers strike\" will have a depressing effect on stock prices whereas terms such as \"earnings rose\" will tend to increase stock prices. When a human trading expert sees certain terms, they will react in a somewhat predictable fashion. AZFinText capitalizes on the arbitrage opportunities that exist when investment experts over and under-react to certain news stories. By analyzing breaking financial news articles and focusing on specific parts of speech, portfolio selection, term weighting and even article sentiment, the AZFinText system becomes a powerful tool and is a radically different way of looking at stock market prediction.",
        "triples": "<AZFinText; full name; Arizona Financial Text System>\n<AZFinText; type; quantitative textual financial prediction system>\n<AZFinText; developers; Robert P. Schumaker and Hsinchun Chen>\n<AZFinText; differences from other systems; uses financial text as one of its key means of predicting stock price movements>\n<AZFinText; the problem the system solves; reduces information lag-time problem in many similar systems>\n<AZFinText; method the system used to solve lag-time problem; utilizing the terms used in financial news articles to predict future stock prices twenty minutes after the news article has been released>\n<AZFinText; how different terms affect stock prices used in the system; Terms such as \"factory exploded\" or \"workers strike\" will have a depressing effect on stock prices whereas terms such as \"earnings rose\" will tend to increase stock prices>\n<AZFinText; strategy of the system; capitalizes on the arbitrage opportunities that exist when investment experts over and under-react to certain news stories>\n<AZFinText; analysis approach of the system; analyzing breaking financial news articles and focusing on specific parts of speech, portfolio selection, term weighting and even article sentiment>", 
    },
    {
        "title": "Baron Ailwyn",
        "text": "Baron Ailwyn, of Honingham in the County of Norfolk, was a title in the Peerage of the United Kingdom. It was created on 1 July 1921 for the Conservative politician the Hon. Sir Ailwyn Fellowes. He was the younger son of Edward Fellowes, 1st Baron de Ramsey. Lord Ailwyn was succeeded by the eldest of his four sons, Ronald, the second Baron. He was a Lieutenant-Colonel in the Rifle Brigade. He was childless and was succeeded by his younger brother Eric, the third Baron. He was a Captain in the Royal Navy. He was also childless and was succeeded by his youngest brother, Carol, the fourth Baron. Like his elder brothers he was childless and the title became extinct on his death in 1988.",
        "triples": "<Baron Ailwyn; location where the title is geographically associated; Honingham in the County of Norfolk>\n<Baron Ailwyn; type; title in the Peerage of the United Kingdom>\n<Baron Ailwyn; creation date; 1 July 1921>\n<Baron Ailwyn; the first individual to hold the title; the Hon. Sir Ailwyn Fellowes>\n<Baron Ailwyn; second holder of the title; Ronald>\n<Baron Ailwyn; occupation of the second holder of the title; a Lieutenant-Colonel in the Rifle Brigade>\n<Baron Ailwyn; the third holder of the title; Eric>\n<Baron Ailwyn; occupation of the third holder of the title; a Captain in the Royal Navy>\n<Baron Ailwyn; the fourth holder of the title; Carol>\n<Baron Ailwyn; when and why the title ceased to exist; title became extinct in 1988>", 
    },
    {
        "title": "Fall into the Open",
        "text": "Fall Into The Open is the first studio album from American Recording Artist, Cris Gunther, released in 2007 on iTunes, CD Baby & Amazon.com. Executived Produced by Cris Gunther, Terry Gunther, and Mary Ann Marchasella. Produced by Tim K (Les Nubians, Tiny Hearts, Russell Taylor, Collette, and Esthero), and Fab Dupont (Shakira, Jennifer Lopez). Written by Cris Gunther, Mic Murphy (The System), Tim K, Fab Dupont, and Richard Lynch. The album features Mic Murphy (The System) on the track, \"Black Doll\", and, Verve/Universal Recording Artist, Lucy Woodward, on the tracks, \"Gotta Give\", \"Sacred Sexuality\", and the Kylie Minogue cover, \"Turn It Into Love\". The album was mixed by Fab Dupont. And, the track, \"The Heat\", was featured in a Songwriter's Hall Of Fame Showcase in New York City in 2002, which was featured in Billboard Magazine. There are ten songs on this recording.",
        "triples": "<Fall into the Open; type; studio album>\n<Fall into the Open; artists of the album; Cris Gunther>\n<Fall into the Open; release date and plateform of the album; 2007 on iTunes, CD Baby & Amazon.com>\n<Fall into the Open; executive producers of the album; Cris Gunther, Terry Gunther, Mary Ann Marchasella>\n<Fall into the Open; producers of the album; Tim K (Les Nubians, Tiny Hearts, Russell Taylor, Collette, and Esthero), and Fab Dupont (Shakira, Jennifer Lopez)>\n<Fall into the Open; songwriters of the album; Cris Gunther, Mic Murphy (The System), Tim K, Fab Dupont, and Richard Lynch>\n<Fall into the Open; artists featured on specific tracks of the album; Mic Murphy (The System) on the track, \"Black Doll\", and, Verve/Universal Recording Artist, Lucy Woodward, on the tracks, \"Gotta Give\", \"Sacred Sexuality\", and the Kylie Minogue cover, \"Turn It Into Love\">\n<Fall into the Open; was mixed by; Fab Dupont>\n<Fall into the Open; recognition received by a specific track; the track, \"The Heat\", was featured in a Songwriter's Hall Of Fame Showcase in New York City in 2002, which was featured in Billboard Magazine>\n<Fall into the Open; number of songs in the album; ten songs>", 
    },
    {
        "title": "Elhovo Gap",
        "text": "Elhovo Gap (Elhovska Sedlovina \\'el-hov-ska se-dlo-vi-'na\\) is a 420 m high saddle extending 1 km in west-southwest\u2013east-northeast direction from Gleaner Heights to Leslie Hill, Livingston Island in the South Shetland Islands, Antarctica which forms part of the overland route between Bowles Ridge and Vidin Heights. The saddle is named after the Bulgarian town of Elhovo, in association with the artificial Christmas tree ('elha' in Bulgarian) brought by the Tangra 2004/05 Survey team (Lyubomir Ivanov and Doychin Vasilev) to their bivouac at Leslie Hill occupied 24\u201328 December 2004, making in the process the first crossing of Elhovo Gap.",
        "triples": "<Elhovo Gap; alias; Elhovska Sedlovina>\n<Elhovo Gap; type; saddle>\n<Elhovo Gap; height; 420 m>\n<Elhovo Gap; location; extending 1 km in west-southwest\u2013east-northeast direction from Gleaner Heights to Leslie Hill, Livingston Island in the South Shetland Islands, Antarctica>\n<Elhovo Gap; geographical importance; forms part of the overland route between Bowles Ridge and Vidin Heights>\n<Elhovo Gap; named after; the Bulgarian town of Elhovo, in association with the artificial Christmas tree ('elha' in Bulgarian) brought by the Tangra 2004/05 Survey team>\n<Elhovo Gap; events; Tangra 2004/05 Survey team brought a tree to their bivouac at Leslie Hill occupied 24\u201328 December 2004, making in the process the first crossing of Elhovo Gap>", 
    },
    {
        "title": "Springs Mills Building",
        "text": "The Springs Mills Building is a 21-story office tower located at 104 West 40th Street and straddles the block with a second entrance on 39th in Manhattan, New York City. The building sits on an L shaped lot that rises to a thin glass hexagonal tower. One of the earliest examples of the International Style in New York, construction occurred between 1961\u201363, designed by the architecture firm Harrison & Abramovitz. The building was designated by the New York City Landmarks Preservation Commission in 2010. Elisabeth de Bourbon, on behalf of the Commission, recognized it as only the eighth Modernist building given the status.",
        "triples": "<Springs Mills Building; type; 21-story office tower>\n<Springs Mills Building; location; 104 West 40th Street and straddles the block with a second entrance on 39th in Manhattan, New York City>\n<Springs Mills Building; architectural feature; sits on an L shaped lot that rises to a thin glass hexagonal tower>\n<Springs Mills Building; construction period; between 1961\u201363>\n<Springs Mills Building; architecture firm responsible for the design; Harrison & Abramovitz>\n<Springs Mills Building; landmark designation; designated by the New York City Landmarks Preservation Commission in 2010>\n<Springs Mills Building; recognition; recognized it as the eighth Modernist building given landmark status>", 
    },
    # 46 - 50 
    {
        "title": "Trichopus zeylanicus",
        "text": "Trichopus zeylanicus is a small herbaceous plant, which is one of only two species of its genus, \"Trichopus\". Formerly it was placed in its own family, Trichopodaceae, but is now included in the Dioscoreaceae family. The leaves are about 20 cm long and grow from a rhizome. The shape of the leaves can be highly variable even within one location, but the most common shape is cordate. The herb grows on sandy soil near rivers and streams in shady places in lowland and intermediate altitude forests. It flowers year long and the fruits are thought to be dispersed by water. The unusual flowers are purplish black.",
        "triples": "<Trichopus zeylanicus; type; a small herbaceous plant>\n<Trichopus zeylanicus; genus to which the plant belongs; Trichopus>\n<Trichopus zeylanicus; previous family classification of the plant; Trichopodaceae>\n<Trichopus zeylanicus; current family classification of the plant; Dioscoreaceae>\n<Trichopus zeylanicus; physical characteristics of the leaves; about 20 cm long and grow from a rhizome. The shape of the leaves can be highly variable even within one location, but the most common shape is cordate>\n<Trichopus zeylanicus; habitat; sandy soil near rivers and streams in shady places in lowland and intermediate altitude forests>\n<Trichopus zeylanicus; flowering period; year long>\n<Trichopus zeylanicus; fruit dispersal method; by water>\n<Trichopus zeylanicus; flower color; purplish black>",
    },
    {
        "title": "1997\u201398 Los Angeles Clippers season",
        "text": "The 1997\u201398 NBA season was the Clippers' 28th season in the National Basketball Association, and their 4th season in Anaheim. During the offseason, the Clippers acquired James Robinson and Stojko Vrankovic from the Minnesota Timberwolves. With Loy Vaught going down early into the season with a back injury after just ten games, the Clippers struggled losing 12 of their first 13 games. Midway through the season, Brent Barry was traded to the Miami Heat for last year's Most Improved Player Isaac Austin. The Clippers lost 15 of their final 17 games, including a 10-game losing streak in April, finishing last place in the Pacific Division with a 17\u201365 record. Lamond Murray led them in scoring with 15.4 points per game, and top draft pick Maurice Taylor made the All-Rookie Second Team. Following the season, Austin signed as a free agent with the Orlando Magic, Vaught signed with the Detroit Pistons, and head coach Bill Fitch was fired.",
        "triples": "<1997\u201398 Los Angeles Clippers season; sports league in which the season occurred; National Basketball Association>\n<1997\u201398 Los Angeles Clippers season; count of seasons the team has played; 28th season in the National Basketball Association>\n<1997\u201398 Los Angeles Clippers season; new players acquired during the offseason; James Robinson and Stojko Vrankovic from the Minnesota Timberwolves>\n<1997\u201398 Los Angeles Clippers season; events; losing 12 of their first 13 games with Loy Vaught going down early into the season with a back injury after just ten games>\n<1997\u201398 Los Angeles Clippers season; events; Brent Barry was traded to the Miami Heat for last year's Most Improved Player Isaac Austin>\n<1997\u201398 Los Angeles Clippers season; events; lost 15 of their final 17 games, including a 10-game losing streak in April, finishing last place in the Pacific Division with a 17\u201365 record>\n<1997\u201398 Los Angeles Clippers season; leading scorer; Lamond Murray>\n<1997\u201398 Los Angeles Clippers season; achievements by rookie players; Maurice Taylor All-Rookie Second Team>\n<1997\u201398 Los Angeles Clippers season; post-season changes; Isaac Austin signed with Orlando Magic>", 
    },
    {
        "title": "Richard Rainey",
        "text": "Richard Rainey was a Republican politician from Walnut Creek, California, a suburb in the San Francisco Bay Area. He served in the California State Assembly from 1992 until 1996 and then served in the State Senate from 1996 until 2000 when he was defeated for reelection by Tom Torlakson, a Democratic Assemblyman from Antioch. In 1995, Mr. Rainey was named Legislator of the Year by the California Probation & Parole Correctional Association. Also, during the 1995-96 legislative session, Mr. Rainey served as Chairman of the Assembly Local Government Committee when the Republicans briefly had a majority in the State Assembly.",
        "triples": "<Richard Rainey; political party; Republican politician from Walnut Creek, California>\n<Richard Rainey; served in; California State Assembly from 1992 until 1996>\n<Richard Rainey; served in; California State Assembly from 1992 until 1996>\n<Richard Rainey; defeated by; Tom Torlakson for reelection>\n<Richard Rainey; award received; Legislator of the Year by the California Probation & Parole Correctional Association in 1995>\n<Richard Rainey; legislative role; served as Chairman of the Assembly Local Government Committee during the 1995-96 legislative session>", 
    },
    {
        "title": "The MoShow",
        "text": "The MoShow is an American syndicated television news program which reviews mobile devices, apps, downloads and text messages. Premiering on January 1, 2011 on over 300 television stations throughout the United States and on DirecTV Channel 354, it is hosted by Mark Yoshimoto Nemcoff (of Pacific Coast Hellway) and Dana Ward (of ClevverTV), with production by Frank Chindamo.",
        "triples": "<The MoShow; type; American syndicated television news program>\n<The MoShow; content scope of the show; reviews mobile devices, apps, downloads, and text messages>\n<The MoShow; premiere date and broadcast reach; on January 1, 2011 over 300 television stations throughout the United States and on DirecTV Channel 354>\n<The MoShow; hosts; Mark Yoshimoto Nemcoff (of Pacific Coast Hellway) and Dana Ward (of ClevverTV)>\n<The MoShow; producer; Frank Chindamo>", 
    },
    {
        "title": "USS General W. F. Hase (AP-146)",
        "text": "USS \"General W. F. Hase\" (AP-146) was a \"General G. O. Squier\"-class transport ship for the US Navy in World War II. She was named in honor of US Army Major General William Frederick Hase. She was transferred to the US Army as USAT \"General W. F. Hase\" in 1946. On 1 March 1950 she was transferred to the Military Sea Transportation Service (MSTS) as USNS \"General W. F. Hase\" (T-AP-146). She was later sold for commercial operation in 1968, before being scrapped in 1985.",
        "triples": "<USS General W. F. Hase (AP-146); type; \"General G. O. Squier\"-class transport ship>\n<USS General W. F. Hase (AP-146); service; US Navy in World War II>\n<USS General W. F. Hase (AP-146); named after; US Army Major General William Frederick Hase>\n<USS General W. F. Hase (AP-146); transferred to; US Army as USAT \"General W. F. Hase\" in 1946>\n<USS General W. F. Hase (AP-146); transferred to; Military Sea Transportation Service (MSTS) as USNS \"General W. F. Hase\" (T-AP-146) on 1 March 1950>\n<USS General W. F. Hase (AP-146); commercial operation; sold for commercial operation in 1968>\n<USS General W. F. Hase (AP-146); final status of the ship; scrapped in 1985>", 
    }
]