
generate_knowledge_triples_musique_examplars = [
    # 1 - 5 
    {
        "title": "Show Me (Jessica Sutta song)",
        "text": "\"Show Me\" is a song by American recording artist Jessica Sutta. The song was written by Alex Geringas, Paddy Dalton and songwriter Busbee, which lyrically talks about how actions talk louder than words. Musically, the song is a club-inspired song. \"Show Me\" premiered on Idolator on August 3, 2011, and was released on August 23, 2011 via Hollywood Records.",
        "triples": "<Show Me (Jessica Sutta song); recording artist; Jessica Sutta>\n<Show Me (Jessica Sutta song); writter; by Alex Geringas, Paddy Dalton and songwriter Busbee>\n<Show Me (Jessica Sutta song); lyrical theme; how actions talk louder than words>\n<Show Me (Jessica Sutta song); musical style; a club-inspired song>\n<Show Me (Jessica Sutta song); premiere date; August 3, 2011>\n<Show Me (Jessica Sutta song); premiere platform; Idolator>\n<Show Me (Jessica Sutta song); release date; August 23, 2011>\n<Show Me (Jessica Sutta song); record label; Hollywood Records>", 
    },
    {
        "title": "A Desert Wooing",
        "text": "A Desert Wooing is a 1918 American drama silent film directed by Jerome Storm and written by J.G. Hawks. The film stars Enid Bennett, Jack Holt, Donald MacDonald, J. P. Lockney and Charles Spere. The film was released on June 23, 1918, by Paramount Pictures. The film has been preserved and was released on DVD format in 2012.",
        "triples": "<A Desert Wooing; release year of the film; 1918>\n<A Desert Wooing; country of origin of the film; American>\n<A Desert Wooing; type of the film; drama silent film>\n<A Desert Wooing; director; Jerome Storm>\n<A Desert Wooing; writer; J.G. Hawks>\n<A Desert Wooing; stars; Enid Bennett, Jack Holt, Donald MacDonald, J. P. Lockney and Charles Spere>\n<A Desert Wooing; release date of the film; June 23, 1918>\n<A Desert Wooing; distributor; Paramount Pictures>\n<A Desert Wooing; status; has been preserved and was released on DVD format in 2012>", 
    },
    {
        "title": "Constitution of the United States",
        "text": "United States Constitution Page one of the original copy of the Constitution Created September 17, 1787 Ratified June 21, 1788 Date effective March 4, 1789; 228 years ago (1789 - 03 - 04) Location National Archives, Washington, D.C. Author (s) Philadelphia Convention Signatories 39 of the 55 delegates Purpose To replace the Articles of Confederation (1777)",
        "triples": "<Constitution of the United States; original copy location; National Archives, Washington, D.C.>\n<Constitution of the United States; creation date; September 17, 1787>\n<Constitution of the United States; ratification date; June 21, 1788>\n<Constitution of the United States; effective date; March 4, 1789>\n<Constitution of the United States; authors; Philadelphia Convention>\n<Constitution of the United States; the number of delegates who signed it; 39 of the 55 delegates>\n<Constitution of the United States; purpose; to replace the Articles of Confederation (1777)>", 
    },
    {
        "title": "Mauricio Mulder",
        "text": "Claude Maurice Mulder Bedoya, known as Mauricio Mulder (born 8 June 1956, in Lima), is a Peruvian politician, lawyer and former journalist. He has served in Congress since 2001. He was reelected for a fourth term in Congress, representing Lima for the APRA-PPC alliance.",
        "triples": "<Mauricio Mulder; full name; Claude Maurice Mulder Bedoya>\n<Mauricio Mulder; date of birth; 8 June 1956>\n<Mauricio Mulder; place of birth; Lima>\n<Mauricio Mulder; nationality; Peruvian>\n<Mauricio Mulder; occupation; politician, lawer and former journalist>\n<Mauricio Mulder; political status; served in Congress since 2001>\n<Mauricio Mulder; congressional term; fourth>\n<Mauricio Mulder; congressional representation; Lima>\n<Mauricio Mulder; political alliance; APRA-PPC>", 
    },
    {
        "title": "Africa",
        "text": "Africa is the world's second - largest and second-most - populous continent (the first being Asia). At about 30.3 million km (11.7 million square miles) including adjacent islands, it covers 6% of Earth's total surface area and 20.4% of its total land area. With 1.2 billion people as of 2016, it accounts for about 16% of the world's human population. The continent is surrounded by the Mediterranean Sea to the north, both the Suez Canal and the Red Sea along the Sinai Peninsula to the northeast, the Indian Ocean to the southeast and the Atlantic Ocean to the west. The continent includes Madagascar and various archipelagos. It contains 54 fully recognised sovereign states (countries), nine territories and two de facto independent states with limited or no recognition.",
        "triples": "<Africa; ranking by size; second-largest continent>\n<Africa; ranking by population; second-most-populous continent>\n<Africa; area; 30.3 million km (11.7 million square miles)>\n<Africa; percentage of Earth's total surface area; 6%>\n<Africa; percentage of Earth's total land area; 20.4%>\n<Africa; population as of 2016; 1.2 billion>\n<Africa; percentage of world's human population; 16%>\n<Africa; northern boundary; Mediterranean Sea>\n<Africa; northeastern boundaries; Suez Canal and Red Sea along the Sinai Peninsula>\n<Africa; southeastern boundary; Indian Ocean>\n<Africa; western boundary; Atlantic Ocean>\n<Africa; islands included; Madagascar and various archipelagos>\n<Africa; number of sovereign states (countries); 54>\n<Africa; number of territories; nine>\n<Africa; number of de facto independent states with limited or no recognition; two>", 
    },
    # 6 - 10 
    {
        "title": "Khabarovsky District",
        "text": "Khabarovsky District () is an administrative and municipal district (raion), one of the seventeen in Khabarovsk Krai, Russia. It consists of two unconnected segments separated by the territory of Amursky District, which are located in the southwest of the krai. The area of the district is . Its administrative center is the city of Khabarovsk (which is not administratively a part of the district). Population:",
        "triples": "<Khabarovsky District; type; administrative and municipal district (raion)>\n<Khabarovsky District; number of districts in Khabarovsk Krai; one of the seventeen>\n<Khabarovsky District; country where the district is located; Russia>\n<Khabarovsky District; geographical features; consists of two unconnected segments separated by the territory of Amursky District>\n<Khabarovsky District; administrative center; city of Khabarovsk>\n<Khabarovsky District; administrative center status; not administratively a part of the district>", 
    },
    {
        "title": "Territory of Papua",
        "text": "In 1949, the Territory and the Territory of New Guinea were established in an administrative union by the name of the Territory of Papua and New Guinea. That administrative union was renamed as Papua New Guinea in 1971. Notwithstanding that it was part of an administrative union, the Territory of Papua at all times retained a distinct legal status and identity; it was a Possession of the Crown whereas the Territory of New Guinea was initially a League of Nations mandate territory and subsequently a United Nations trust territory. This important legal and political distinction remained until the advent of the Independent State of Papua New Guinea in 1975.",
        "triples": "<Territory of Papua; established administrative union with; Territory of New Guinea>\n<Territory of Papua; name of administrative union established in 1949; Territory of Papua and New Guinea>\n<Territory of Papua; new name of the administrative union in 1971; Papua New Guinea>\n<Territory of Papua; legal status; Possession of the Crown>\n<Territory of Papua; the year until which the Territory of Papua retained its distinct legal status; 1975>\n<Territory of Papua; became part of; Independent State of Papua New Guinea>", 
    },
    {
        "title": "Land Titles Building (Arcola)",
        "text": "The Land Titles Building is located at 301 Main Street in Arcola, Saskatchewan, Canada. The architectural firm of Storey and Van Egmond designed the building. The building is a designated Heritage Property. The building housed land title records until the 1960s; due to the importance of these records the building was designed to be fire-proof and therefore the walls, floor, ceiling and doors were all made of metal, brick or stone.",
        "triples": "<Land Titles Building (Arcola); location; 301 Main Street in Arcola, Saskatchewan, Canada>\n<Land Titles Building (Arcola); architectural firm; Storey and Van Egmond>\n<Land Titles Building (Arcola); heritage status; designated Heritage Property>\n<Land Titles Building (Arcola); function until the 1960s; housed land title records>\n<Land Titles Building (Arcola); design feature; fire-proof>\n<Land Titles Building (Arcola); materials used for the walls, floor, ceiling and doors; metal, brick or stone>", 
    },
    {
        "title": "United Nations Security Council Resolution 835",
        "text": "United Nations Security Council resolution 835, adopted unanimously on 2 June 1993, after recalling resolutions 668 (1990), 745 (1992), 810 (1993), 826 (1993) and other relevant resolutions, the Council expressed appreciation for the United Nations Transitional Authority in Cambodia (UNTAC) in the aftermath of recent elections in Cambodia.",
        "triples": "<United Nations Security Council Resolution 835; adoption date; 2 June 1993>\n<United Nations Security Council Resolution 835; adoption method; unanimously>\n<United Nations Security Council Resolution 835; recalled resolutions; 668 (1990), 745 (1992), 810 (1993), 826 (1993) and other relevant resolutions>\n<United Nations Security Council Resolution 835; appreciation expressed for; United Nations Transitional Authority in Cambodia (UNTAC)>\n<United Nations Security Council Resolution 835; situation in which appreciation was expressed; aftermath of recent elections in Cambodia>", 
    },
    {
        "title": "EMC EA/EB",
        "text": "The EMC EA/EB was an early passenger train-hauling diesel locomotive built in May 16, 1937 \u2013 1938 by Electro-Motive Corporation of La Grange, Illinois for the Baltimore and Ohio Railroad. They were the first model in a long line of passenger diesels of similar design known as EMD E-units. Each locomotive unit developed from two Winton 201-A diesel engines, driving the wheels through an electric transmission\u2014the generator driven by each engine provided current for traction motors. The locomotives were of A1A-A1A wheel arrangement\u2014two three-axle trucks of which only the outer two axles were powered. Six two-unit locomotives were produced, each consisting of a lead cab-equipped EA A unit and a cabless booster EB B unit. They were numbered 51 through 56; the A units bore the bare number and the B units the number followed by 'X'.",
        "triples": "<EMC EA/EB; type; early passenger train-hauling diesel locomotive>\n<EMC EA/EB; period when the locomotive was built; May 16, 1937 \u2013 1938>\n<EMC EA/EB; manufacturer; Electro-Motive Corporation of La Grange, Illinois>\n<EMC EA/EB; built for; Baltimore and Ohio Railroad>\n<EMC EA/EB; first model in series; EMD E-units>\n<EMC EA/EB; developed from engines; two Winton 201-A diesel engines>\n<EMC EA/EB; wheel arrangement; A1A-A1A>\n<EMC EA/EB; number of locomotives produced; six two-unit locomotives>\n<EMC EA/EB; composition of each locomotive unit; lead cab-equipped EA A unit and cabless booster EB B unit>\n<EMC EA/EB; unit numbering; 51 through 56>\n<EMC EA/EB; unit numbering; A units bore the bare number and the B units the number followed by 'X'>", 
    },
    # 11 - 15 
    {
        "title": "HR 2096",
        "text": "HR 2096, also known as HD 40325 is a double star in the constellation Auriga. It is composed of two ageing orange giants of spectral types K0III and K2III. It is not a member of any known moving group of stars.",
        "triples": "<HR 2096; also known as; HD 40325>\n<HR 2096; type; a double star in the constellation Auriga>\n<HR 2096; components; two ageing orange giants of spectral types K0III and K2III>\n<HR 2096; membership; not a member of any known moving group of stars>", 
    },
    {
        "title": "Binodanand Jha",
        "text": "Binodanand Jha (17 April 1900 - 1971), also known as Pandit Binodanand Jha, was an Indian politician originally from the district of Deoghar, Bihar (Baidyanathdham Deoghar) now in Jharkhand. He was educated at the Central Calcutta College, (now Maulana Azad College) under the University of Calcutta. He was the Chief Minister of Bihar from February 1961 to October 1963. He was elected to the 5th Lok Sabha, lower house of the Parliament of India from the Darbhanga constituency of Bihar in 1971. He was a member of the Constituent Assembly of India in 1948 from Bihar.",
        "triples": "<Binodanand Jha; date of birth; 17 April 1900>\n<Binodanand Jha; year of death; 1971>\n<Binodanand Jha; also known as; Pandit Binodanand Jha>\n<Binodanand Jha; nationality; Indian>\n<Binodanand Jha; occupation; politician>\n<Binodanand Jha; place of origin; district of Deoghar, Bihar>\n<Binodanand Jha; current place of origin; Jharkhand>\n<Binodanand Jha; education; Central Calcutta College under the University of Calcutta>\n<Binodanand Jha; position; Chief Minister of Bihar from February 1961 to October 1963>\n<Binodanand Jha; political activity; elected to the 5th Lok Sabha, lower house of the Parliament of India from the Darbhanga constituency of Bihar in 1971>\n<Binodanand Jha; membership; member of the Constituent Assembly of India in 1948 from Bihar>", 
    },
    {
        "title": "A Jackson in Your House",
        "text": "A Jackson in Your House is a 1969 album by the Art Ensemble of Chicago recorded for the French BYG Actuel label. It features performances by Lester Bowie, Joseph Jarman, Roscoe Mitchell and Malachi Favors Maghostut. When issued on CD by Affinity in 1989, the track \"The Waltz\" was replaced by a six-minute live excerpt (of unknown provenance) entitled \"Hey Friend\" which has never reappeared on any subsequent reissue.",
        "triples": "<A Jackson in Your House; type; a 1969 album>\n<A Jackson in Your House; artist; Art Ensemble of Chicago>\n<A Jackson in Your House; record label; French BYG Actuel label>\n<A Jackson in Your House; artists who performed on the album; Lester Bowie, Joseph Jarman, Roscoe Mitchell and Malachi Favors Maghostut>\n<A Jackson in Your House; the label that issued the CD version in 1989; Affinity>\n<A Jackson in Your House; track replacement on reissue; the track \"The Waltz\" was replaced by a six-minute live excerpt (of unknown provenance) entitled \"Hey Friend\">", 
    },
    {
        "title": "Hugh Aiken Bayne",
        "text": "Hugh Aiken Bayne (15 February 1870 in New Orleans \u2013 24 December 1954 in New Haven, Connecticut) was the son of Thomas Levingston Bayne, a lawyer who fought in the Civil War. His grandfather John Gayle was a Congressman and Governor of Alabama.",
        "triples": "<Hugh Aiken Bayne; date of birth; 15 February 1870>\n<Hugh Aiken Bayne; place of birth; New Orleans>\n<Hugh Aiken Bayne; date of death; 24 December 1954>\n<Hugh Aiken Bayne; place of death; New Haven, Connecticut>\n<Hugh Aiken Bayne; father; Thomas Levingston Bayne>\n<Hugh Aiken Bayne; father's position; a lawyer who fought in the Civil War>\n<Hugh Aiken Bayne; grandfather; John Gayle>\n<Hugh Aiken Bayne; position of his grandfather; Congressman and Governor of Alabama>", 
    },
    {
        "title": "Your Love Is a Song",
        "text": "\"Your Love Is a Song\" was written and recorded by the alternative rock band Switchfoot. It was first released as a single to the iTunes Store in Australia, and became the third radio single from the band's seventh studio album, \"Hello Hurricane\".",
        "triples": "<Your Love Is a Song; writer; alternative rock band Switchfoot>\n<Your Love Is a Song; performer; alternative rock band Switchfoot>\n<Your Love Is a Song; initial release platform; iTunes Store in Australia>\n<Your Love Is a Song; status; became the third radio single from the band's seventh studio album, \"Hello Hurricane\">", 
    },
    # 16 - 20 
    {
        "title": "World War II",
        "text": "World War II (left to right, starting from top row) US transports unload onto the Normandy coast during Operation Overlord Reichstag building in the aftermath of the Battle of Berlin Supermarine Spitfire formation in 1940 German troops raise the Swastika over the Acropolis of Athens Japanese battleship Yamato being attacked by US aircraft during Operation Ten - Go Soviet soldiers in a forward position during Operation Bagration Wilhelm Keitel signing the German Instrument of Surrender Troops of the United States Army fire on Japanese positions during the Bougainville Campaign in March 1944 Waffen - SS soldier during the Battle of the Bulge Soviet troops during the Battle of Stalingrad Sinking of the British merchant ship ``Beacon Grange ''by German submarine U-552 Panzer IVs advance on the Eastern Front in 1943 Date 1 September 1939 -- 2 September 1945 (1939 - 09 - 01 -- 1945 - 09 - 02) (6 years and 1 day) Location Europe, Pacific, Atlantic, South - East Asia, China, Middle East, Mediterranean, North Africa, Horn of Africa, Australia, briefly North and South America Result Allied victory Collapse of Nazi Germany Fall of Japanese and Italian Empires Dissolution of the League of Nations Creation of the United Nations Emergence of the United States and the Soviet Union as rival superpowers Beginning of the Cold War (more...) Participants Allied Powers Axis Powers Commanders and leaders Main Allied leaders Joseph Stalin Franklin D. Roosevelt Winston Churchill Chiang Kai - shek Main Axis leaders Adolf Hitler Hirohito Benito Mussolini Casualties and losses Military dead: Over 16,000,000 Civilian dead: Over 45,000,000 Total dead: Over 61,000,000 (1937 -- 45)... further details Military dead: Over 8,000,000 Civilian dead: Over 4,000,000 Total dead: Over 12,000,000 (1937 -- 45)... further details",
        "triples": "<World War II; events; US transports unload onto the Normandy coast during Operation Overlord Reichstag building in the aftermath of the Battle of Berlin Supermarine Spitfire formation in 1940>\n<World War II; events; German troops raise the Swastika over the Acropolis of Athens>\n<World War II; events; Japanese battleship Yamato being attacked by US aircraft during Operation Ten>\n<World War II; events; Go Soviet soldiers in a forward position during Operation Bagration Wilhelm Keitel signing the German Instrument of Surrender>\n<World War II; events; Troops of the United States Army fire on Japanese positions during the Bougainville Campaign in March 1944 Waffen>\n<World War II; events; during the Battle of the Bulge Soviet troops during the Battle of Stalingrad Sinking of the British merchant ship ``Beacon Grange ''by German submarine U-552 Panzer IVs>\n<World War II; period; 1 September 1939 to 2 September 1945>\n<World War II; duration; 6 years and 1 day>\n<World War II; regions where the war took place; Europe, Pacific, Atlantic, South - East Asia, China, Middle East, Mediterranean, North Africa, Horn of Africa, Australia, briefly North and South America>\n<World War II; result; Allied victory Collapse of Nazi Germany, fall of Japanese and Italian Empires, dissolution of the League of Nations, creation of the United Nations, emergence of the United States and the Soviet Union as rival superpowers, beginning of the Cold War>\n<World War II; participants; Allied Powers, Axis Powers>\n<World War II; main Allied leaders; Joseph Stalin, Franklin D. Roosevelt, Winston Churchill, Chiang Kai-shek>\n<World War II; main Axis leaders; Adolf Hitler, Hirohito, Benito Mussolini>\n<World War II; military dead; over 16,000,000>\n<World War II; civilian dead; over 45,000,000>\n<World War II; total dead; over 61,000,000>\n<World War II; military dead (1937-1945); over 8,000,000>\n<World War II; civilian dead (1937-1945); over 4,000,000>\n<World War II; total dead (1937-1945); over 12,000,000>", 
    },
    {
        "title": "Bogot\u00e1",
        "text": "Bogot\u00e1 (/ \u02c8bo\u028a\u0261\u0259t\u0251\u02d0 /, / \u02ccb\u0252\u0261\u0259\u02c8t\u0251\u02d0 /, / \u02ccbo\u028a - /; Spanish pronunciation: (bo\u0263o\u02c8ta) (listen)), officially Bogot\u00e1, Distrito Capital, abbreviated Bogot\u00e1, D.C., and formerly known as Santaf\u00e9 de Bogot\u00e1 between 1991 and 2000, is the capital and largest city of Colombia, administered as the Capital District, although often thought of as part of Cundinamarca. Bogot\u00e1 is a territorial entity of the first order, with the same administrative status as the departments of Colombia. It is the political, economic, administrative, industrial, artistic, cultural, and sports center of the country.",
        "triples": "<Bogot\u00e1; official name; Bogot\u00e1, Distrito Capital>\n<Bogot\u00e1; abbreviation; Bogot\u00e1, D.C.>\n<Bogot\u00e1; former name; Santaf\u00e9 de Bogot\u00e1 between 1991 and 2000>\n<Bogot\u00e1; status; capital and largest city of Colombia>\n<Bogot\u00e1; administrative division; Capital District>\n<Bogot\u00e1; association; part of Cundinamarca>\n<Bogot\u00e1; administrative status; territorial entity of the first order>\n<Bogot\u00e1; same administrative status as; departments of Colombia>\n<Bogot\u00e1; city's functions; political, economic, administrative, industrial, artistic, cultural, and sports center>", 
    },
    {
        "title": "Monastery of the Virgins",
        "text": "The Monastery of the Virgins is a structure uncovered during Benjamin Mazar's excavations south of Jerusalem's Temple Mount. The large number of Christian religious finds from the site have prompted its identification with a monastery described by a pilgrim, Theodosius the archdeacon, in his \"De Situ Terrae Sanctae\", a work of the early 6th century. The building was constructed in the 4th century on the remains of an earlier Herodian building identified with the Second Temple courthouse, and was destroyed during the Persian sack of Jerusalem in 614.",
        "triples": "<Monastery of the Virgins; location; south of Jerusalem's Temple Mount>\n<Monastery of the Virgins; uncovered during; Benjamin Mazar's excavations>\n<Monastery of the Virgins; the reason for identifying the structure with a monastery; large number of Christian religious finds>\n<Monastery of the Virgins; described by; Theodosius the archdeacon>\n<Monastery of the Virgins; the work where the monastery is described; De Situ Terrae Sanctae>\n<Monastery of the Virgins; the time period of the description; early 6th century>\n<Monastery of the Virgins; construction date; 4th century>\n<Monastery of the Virgins; built on remains of; earlier Herodian building>\n<Monastery of the Virgins; earlier building identified with; Second Temple courthouse>\n<Monastery of the Virgins; destruction event; Persian sack of Jerusalem>\n<Monastery of the Virgins; destruction year; 614>", 
    },
    {
        "title": "Vilnius County",
        "text": "Vilnius County () is the largest of the 10 counties of Lithuania, located in the east of the country around the city Vilnius. On 1 July 2010, the county administration was abolished, and since that date, Vilnius County remains as the territorial and statistical unit.",
        "triples": "<Vilnius County; size; largest of the 10 counties of Lithuania>\n<Vilnius County; location; in the east of the country around the city Vilnius>\n<Vilnius County; the date when the county administration was abolished; 1 July 2010>\n<Vilnius County; current status; territorial and statistical unit>", 
    },
    {
        "title": "Foar",
        "text": "Foar is a town in the northeastern Bari region of Somalia, on the coast of the Guardafui Channel. It is a center for the local lobster market.",
        "triples": "<Foar; type; town>\n<Foar; location; in the northeastern Bari region of Somalia, on the coast of the Guardafui Channel>\n<Foar; economic activity; center for the local lobster market>", 
    },
    # 21 - 25 
    {
        "title": "American Idol",
        "text": "American Idol employs a panel of judges who critique the contestants' performances. The original judges were record producer and music manager Randy Jackson, pop singer and choreographer Paula Abdul and music executive and manager Simon Cowell. The judging panel for the most recent season consisted of country singer Keith Urban, singer and actress Jennifer Lopez, and jazz singer Harry Connick, Jr. The show was originally hosted by radio personality Ryan Seacrest and comedian Brian Dunkleman, with Seacrest continuing on for the rest of the seasons.",
        "triples": "<American Idol; content; employs a panel of judges who critique the contestants' performances>\n<American Idol; original judges; record producer and music manager Randy Jackson, pop singer and choreographer Paula Abdul and music executive and manager Simon Cowell>\n<American Idol; judges for the most recent season; country singer Keith Urban, singer and actress Jennifer Lopez, and jazz singer Harry Connick, Jr.>\n<American Idol; original host; radio personality Ryan Seacrest and comedian Brian Dunkleman>\n<American Idol; host who continued for the rest of the seasons; Ryan Seacrest>", 
    },
    {
        "title": "Portugal",
        "text": "The Portuguese language is derived from the Latin spoken by the romanized Pre-Roman peoples of the Iberian Peninsula around 2000 years ago\u2014particularly the Celts, Tartessians, Lusitanians and Iberians. In the 15th and 16th centuries, the language spread worldwide as Portugal established a colonial and commercial empire between 1415 and 1999. Portuguese is now spoken as a native language in five different continents, with Brazil accounting for the largest number of native Portuguese speakers of any country (200 million speakers in 2012).",
        "triples": "<Portugal; language derived from; Latin spoken by the romanized Pre-Roman peoples of the Iberian Peninsula>\n<Portugal; groups whose language influenced Portuguese; Celts, Tartessians, Lusitanians and Iberians>\n<Portugal; time during which Portuguese spread worldwide; 15th and 16th centuries>\n<Portugal; reason for the spread of the Portuguese language; Portugal established a colonial and commercial empire between 1415 and 1999>\n<Portugal; global presence of the Portuguese language; five different continents>\n<Portugal; largest number of native Portuguese speakers; Brazil>\n<Portugal; number of Portuguese speakers in Brazil (2012); 200 million>", 
    },
    {
        "title": "Paea",
        "text": "Paea is a commune in the suburbs of Papeete in French Polynesia, an overseas territory of France in the southern Pacific Ocean. Paea is located on the island of Tahiti, in the administrative subdivision of the Windward Islands, themselves part of the Society Islands. At the 2017 census it had a population of 13,021.",
        "triples": "<Paea; type; commune>\n<Paea; location; suburbs of Papeete in French Polynesia, an overseas territory of France in the southern Pacific Ocean>\n<Paea; island where Paea is located; Tahiti>\n<Paea; administrative subdivision; Windward Islands>\n<Paea; larger group of islands that includes the Windward Islands; Society Islands>\n<Paea; population count from the 2017 census; 13,021>", 
    },
    {
        "title": "WKCM",
        "text": "WKCM (1160 AM) is an American radio station licensed to serve the community of Hawesville, Kentucky. The station is owned and operated by Hancock Communications, Inc., doing business as the Cromwell Radio Group, and the station's broadcast license is held by Hancock Communications, Inc.",
        "triples": "<WKCM; radio frequency; 1160 AM>\n<WKCM; type; American radio station>\n<WKCM; function; licensed to serve the community of Hawesville, Kentucky>\n<WKCM; owner and operator; Hancock Communications, Inc.>\n<WKCM; broadcast license holder; Hancock Communications, Inc.>", 
    },
    {
        "title": "List of countries by GDP (nominal)",
        "text": "The United States is the world's largest economy with a GDP of approximately $19.39 trillion, notably due to high average incomes, a large population, capital investment, moderate unemployment, high consumer spending, a relatively young population, and technological innovation. Tuvalu is the world's smallest national economy, with a GDP of about $32 million, because of its very small population, a lack of natural resources, reliance on foreign aid, negligible capital investment, demographic problems, and low average incomes.",
        "triples": "<List of countries by GDP (nominal); the world's largest economy; United States>\n<List of countries by GDP (nominal); GDP of United States; approximately $19.39 trillion>\n<List of countries by GDP (nominal); reasons for high GDP of United States; high average incomes, a large population, capital investment, moderate unemployment, high consumer spending, a relatively young population, and technological innovation>\n<List of countries by GDP (nominal); smallest national economy; Tuvalu>\n<List of countries by GDP (nominal); GDP of Tuvalu; about $32 million>\n<List of countries by GDP (nominal); reasons for low GDP of Tuvalu; very small population, a lack of natural resources, reliance on foreign aid, negligible capital investment, demographic problems, and low average incomes>", 
    },
    # 26 - 30 
    {
        "title": "Lord of the Nutcracker Men",
        "text": "Lord of the Nutcracker Men is a novel by Canadian author Iain Lawrence that takes place in England during the first year of World War I. The book was first published in October 2001 by the Delacorte Press, and it was later reprinted in May 2003 by Dell-Laurel Leaf, an imprint of a division of Random House, Inc. The book has become a bestseller, and is included in the required reading lists of many American high schools.",
        "triples": "<Lord of the Nutcracker Men; type; novel>\n<Lord of the Nutcracker Men; writer; Iain Lawrence>\n<Lord of the Nutcracker Men; place and time of the story; England during the first year of World War I>\n<Lord of the Nutcracker Men; first publication date; October 2001>\n<Lord of the Nutcracker Men; first publisher; Delacorte Press>\n<Lord of the Nutcracker Men; reprint date; May 2003>\n<Lord of the Nutcracker Men; reprint publisher; Dell-Laurel Leaf>\n<Lord of the Nutcracker Men; division of the reprint publisher; Random House, Inc.>\n<Lord of the Nutcracker Men; status; become a bestseller, and is included in the required reading lists of many American high schools>", 
    },
    {
        "title": "Falls High School",
        "text": "Falls High School is a public high school located in International Falls, Minnesota. The school's class ring design is the oldest class ring tradition in the United States, dating back to 1929. As of 2014 approximately 600 students attend classes in the school. Every grade level ranges from 70-100 students. In the Fall of 2014 the school changed policies and changed over from a 6 period day to a 7 period day. The students have 5 minutes between each class to maneuver to the next one.",
        "triples": "<Falls High School; type; public high school>\n<Falls High School; location; International Falls, Minnesota>\n<Falls High School; school's notable class ring design; oldest in the United States, dating back to 1929>\n<Falls High School; number of students attending the school as of 2014; approximately 600>\n<Falls High School; number of students per grade level; 70-100>\n<Falls High School; schedule change; the school changed policies and changed over from a 6 period day to a 7 period day>\n<Falls High School; schedule change date; Fall of 2014>\n<Falls High School; time between classes; 5 minutes>", 
    },
    {
        "title": "2000\u201301 WPHL season",
        "text": "The 2000-01 Western Professional Hockey League season was the fifth and final season of the Western Professional Hockey League, a North American minor pro league. 14 teams participated in the regular season, and the Bossier-Shreveport Mudbugs were the league champions.",
        "triples": "<2000\u201301 WPHL season; full name; 2000-01 Western Professional Hockey League season>\n<2000\u201301 WPHL season; league name; Western Professional Hockey League>\n<2000\u201301 WPHL season; season number; fifth and final season>\n<2000\u201301 WPHL season; location; North America>\n<2000\u201301 WPHL season; professional level of the league; minor pro league>\n<2000\u201301 WPHL season; number of teams participated in the season; 14>\n<2000\u201301 WPHL season; league champions; Bossier-Shreveport Mudbugs>", 
    },
    {
        "title": "Ines Cassettari",
        "text": "Ines Cassettari (died 1943) was an Italian emigrant to America whose autobiography became famous. She was born in 1866 or 1867 in Lombardy, Italy, and abandoned at birth, and lived in an orphanage and then a foster home. She was forced to marry an abusive man. They immigrated to the United States, where she refused to run a brothel for him and eventually left him. She remarried and worked as a cleaning woman in the Chicago Commons until she died.",
        "triples": "<Ines Cassettari; year of death; 1943>\n<Ines Cassettari; nationality; Italian>\n<Ines Cassettari; notable work; autobiography>\n<Ines Cassettari; year of birth; 1866 or 1867>\n<Ines Cassettari; place of birth; Lombardy, Italy>\n<Ines Cassettari; early life; abandoned at birth, and lived in an orphanage and then a foster home>\n<Ines Cassettari; first husbund; an abusive man>\n<Ines Cassettari; place where she immigrated to; United States>\n<Ines Cassettari; reason she left her husband; refused to run a brothel for him>\n<Ines Cassettari; her job in the United States; cleaning woman>\n<Ines Cassettari; place where she worked until she died; Chicago Commons>", 
    },
    {
        "title": "List of Florida hurricanes",
        "text": "The List of Florida hurricanes encompasses approximately 500 tropical or subtropical cyclones that affected the state of Florida. More storms hit Florida than any other U.S. state, and since 1851 only eighteen hurricane seasons passed without a known storm impacting the state. Collectively, cyclones that hit the region have resulted in over 10,000 deaths, most of which occurring prior to the start of Hurricane Hunters flights in 1943. Additionally, the cumulative impact from the storms totaled over $141 billion in damage (2017 USD), primarily from Hurricane Andrew and hurricanes in the 2004 and 2005 seasons.",
        "triples": "<List of Florida hurricanes; total number of tropical or subtropical cyclones affecting Florida; approximately 500>\n<List of Florida hurricanes; number of hurricane seasons since 1851 without a known storm impacting Florida; eighteen>\n<List of Florida hurricanes; number of deaths caused by cyclones hitting Florida; over 10,000>\n<List of Florida hurricanes; period when most of the deaths occurred; prior to the start of Hurricane Hunters flights in 1943>\n<List of Florida hurricanes; cumulative financial impact of the storms; over $141 billion (2017 USD)>\n<List of Florida hurricanes; main storms responsible for the majority of the financial damage; Hurricane Andrew and hurricanes in the 2004 and 2005 seasons>", 
    },
    # 31 - 35 
    {
        "title": "Raush River",
        "text": "The Raush River is a tributary of the Fraser River in British Columbia, Canada. It drains a watershed of approximately on the eastern flanks of the Cariboo Mountains, a sub-range of the Columbia Mountains. The river joins the Fraser near the community of Dunster in the Robson Valley. The river's name is the result of a transcription error; it was originally called the \"Rivi\u00e8re au Shuswap\", this was recorded on some maps as \"R.auSh.\", which then became \"Raush\" on official maps. Its source is the Raush Glacier, and major tributary creeks include Black Martin and Quanstrom.",
        "triples": "<Raush River; type; tributary>\n<Raush River; primary river; Fraser River>\n<Raush River; location; British Columbia, Canada>\n<Raush River; region it drains; eastern flanks of the Cariboo Mountains>\n<Raush River; place where the it joins the Fraser; near the community of Dunster in the Robson Valley>\n<Raush River; origin of its name; transcription error>\n<Raush River; original name; Rivi\u00e8re au Shuswap>\n<Raush River; source; Raush Glacier>\n<Raush River; major tributary creeks; Black Martin and Quanstrom>", 
    },
    {
        "title": "Mount Franklin (Australian Capital Territory)",
        "text": "Mount Franklin is a mountain with an elevation of in the Brindabella Ranges that is located on the border between the Australian Capital Territory and New South Wales, Australia. The summit of the mountain is located in the Australian Capital Territory.",
        "triples": "<Mount Franklin (Australian Capital Territory); type; mountain>\n<Mount Franklin (Australian Capital Territory); mountain range where Mount Franklin is located; Brindabella Ranges>\n<Mount Franklin (Australian Capital Territory); location; border between the Australian Capital Territory and New South Wales, Australia>\n<Mount Franklin (Australian Capital Territory); summit location; Australian Capital Territory>", 
    },
    {
        "title": "Sino-Tibetan relations during the Ming dynasty",
        "text": "According to Chen, the Ming officer of Hezhou (modern day Linxia) informed the Hongwu Emperor that the general situation in Dbus and Gtsang \"was under control,\" and so he suggested to the emperor that he offer the second Phagmodru ruler, Jamyang Shakya Gyaltsen, an official title. According to the Records of the Founding Emperor, the Hongwu Emperor issued an edict granting the title \"Initiation State Master\" to Sagya Gyaincain, while the latter sent envoys to the Ming court to hand over his jade seal of authority along with tribute of colored silk and satin, statues of the Buddha, Buddhist scriptures, and sarira.",
        "triples": "<Sino-Tibetan relations during the Ming dynasty; events; Ming officer of Hezhou (modern day Linxia) informed the Hongwu Emperor that the general situation in Dbus and Gtsang \"was under control,\">\n<Sino-Tibetan relations during the Ming dynasty; suggestion to Hongwu Emperor; offer an official title to Jamyang Shakya Gyaltsen>\n<Sino-Tibetan relations during the Ming dynasty; action taken by the Hongwu Emperor; issued an edict granting the title \"Initiation State Master\" to Sagya Gyaincain>\n<Sino-Tibetan relations during the Ming dynasty; action taken by Sagya Gyaincain; sent envoys to the Ming court to hand over his jade seal of authority along with tribute of colored silk and satin, statues of the Buddha, Buddhist scriptures, and sarira>", 
    },
    {
        "title": "Mount Keinath",
        "text": "Mount Keinath () is a mountain, high, rising at the east side of the terminus of Boomerang Glacier in the Deep Freeze Range, Victoria Land, Antarctica. It was mapped by the United States Geological Survey from surveys and U.S. Navy air photos, 1955\u201363, and was named by the Advisory Committee on Antarctic Names for Gerald E. Keinath, a biolab administrator at McMurdo Station in the 1965\u201366 season.",
        "triples": "<Mount Keinath; type; mountain>\n<Mount Keinath; elevation; high>\n<Mount Keinath; location; east side of the terminus of Boomerang Glacier in the Deep Freeze Range, Victoria Land, Antarctica>\n<Mount Keinath; organization that mapped Mount Keinath; United States Geological Survey>\n<Mount Keinath; mapping period; 1955\u201363>\n<Mount Keinath; named by; Advisory Committee on Antarctic Names for Gerald E. Keinath>\n<Mount Keinath; role of Gerald E. Keinath; biolab administrator at McMurdo Station>\n<Mount Keinath; time frame when Gerald E. Keinath served; 1965\u201366 season>", 
    },
    {
        "title": "2018 United States House of Representatives elections",
        "text": "The 2018 United States House of Representatives elections will be held on November 6, 2018. Elections will be held to elect representatives from all 435 congressional districts across each of the 50 U.S. states. Non-voting delegates from the District of Columbia and four of the five inhabited U.S. territories will also be elected. The winners of this election will serve in the 116th United States Congress, with seats apportioned among the states based on the 2010 United States Census. Republicans have held a House majority since January 2011 (see 2010 results), although they lost six seats in the 2016 elections.",
        "triples": "<2018 United States House of Representatives elections; election date; November 6, 2018>\n<2018 United States House of Representatives elections; purpose; elect representatives from all 435 congressional districts across each of the 50 U.S. states>\n<2018 United States House of Representatives elections; areas where non-voting delegates will be elected; District of Columbia and four of the five inhabited U.S. territories>\n<2018 United States House of Representatives elections; Congress session for which the winners will serve; 116th United States Congress>\n<2018 United States House of Representatives elections; seats apportioned based on; 2010 United States Census>\n<2018 United States House of Representatives elections; Republican majority since; January 2011>\n<2018 United States House of Representatives elections; Republican seat loss; six seats in the 2016 elections>", 
    },
    # 36 - 40 
    {
        "title": "Miami",
        "text": "Miami has a tropical monsoon climate (K\u00f6ppen climate classification Am) with hot and humid summers and short, warm winters, with a marked drier season in the winter. Its sea-level elevation, coastal location, position just above the Tropic of Cancer, and proximity to the Gulf Stream shapes its climate. With January averaging 67.2 \u00b0F (19.6 \u00b0C), winter features mild to warm temperatures; cool air usually settles after the passage of a cold front, which produces much of the little amount of rainfall during the season. Lows occasionally fall below 50 \u00b0F (10 \u00b0C), but very rarely below 35 \u00b0F (2 \u00b0C). Highs generally range between 70\u201377 \u00b0F (21\u201325 \u00b0C).",
        "triples": "<Miami; classification of Miami's climate; tropical monsoon climate>\n<Miami; summer climate; hot and humid>\n<Miami; winter climate; short, warm>\n<Miami; drier season; winter>\n<Miami; factors shaping Miami's climate; sea-level elevation, coastal location, position just above the Tropic of Cancer, and proximity to the Gulf Stream>\n<Miami; average temperature in January; 67.2 \u00b0F (19.6 \u00b0C)>\n<Miami; general temperature in winter; mild to warm temperatures>\n<Miami; cool air occurrence; after the passage of a cold front>\n<Miami; occasional low temperatures; below 50 \u00b0F (10 \u00b0C)>\n<Miami; rare low temperatures; below 35 \u00b0F (2 \u00b0C)>\n<Miami; high temperature range in winter; 70\u201377 \u00b0F (21\u201325 \u00b0C)>", 
    },
    {
        "title": "Louis Lacombe",
        "text": "Louis Lacombe was born in Bourges, the brother of composer Felicita Casella. He showed unusual musical abilities at very young age and was soon hailed as a child prodigy. He studied piano at the Paris Conservatoire from 1829 to 1832 with Pierre Zimmerman and won first prize in piano performance at only age 12 in 1831. He began touring Western Europe after leaving the Conservatoire, and in 1834 he studied composition in Vienna with Carl Czerny, and theory with Ignaz von Seyfried and Simon Sechter. At the end of the decade, he settled in Paris and married his first wife; his second wife, Andrea Lacombe (n\u00e9e Favel), whom he married in 1869, was a singer.",
        "triples": "<Louis Lacombe; place of birth; Bourges>\n<Louis Lacombe; sibling; Felicita Casella>\n<Louis Lacombe; early musical ability; showed unusual musical abilities at very young age>\n<Louis Lacombe; recognition; child prodigy>\n<Louis Lacombe; place where he studied piano; Paris Conservatoire>\n<Louis Lacombe; piano teacher; Pierre Zimmerman>\n<Louis Lacombe; period during which he studied piano; from 1829 to 1832>\n<Louis Lacombe; awards; won first prize in piano performance at only age 12 in 1831>\n<Louis Lacombe; post-Conservatoire activity; touring Western Europe>\n<Louis Lacombe; place where he studied composition; Vienna>\n<Louis Lacombe; composition teacher; Carl Czerny>\n<Louis Lacombe; theory teachers; Ignaz von Seyfried and Simon Sechter>\n<Louis Lacombe; settlement; Pairs>\n<Louis Lacombe; first wife; unknown>\n<Louis Lacombe; second wife; Andrea Lacombe (n\u00e9e Favel)>\n<Louis Lacombe; second wife's profession; singer>\n<Louis Lacombe; second marriage year; 1869>", 
    },
    {
        "title": "Halcyonair",
        "text": "Halcyonair, S.A. was an airline with its head office in Am\u00edlcar Cabral International Airport in Espargos, Sal, Cape Verde. It was established in April 2005 and operated domestic flights between the Cape Verde Islands from its main base Am\u00edlcar Cabral International Airport.",
        "triples": "<Halcyonair; type; airline>\n<Halcyonair; head office location; Am\u00edlcar Cabral International Airport in Espargos, Sal, Cape Verde>\n<Halcyonair; establishment date; April 2005>\n<Halcyonair; type of flights the airline operated; domestic flights>\n<Halcyonair; service area; between the Cape Verde Islands from its main base Am\u00edlcar Cabral International Airport>", 
    },
    {
        "title": "China at the Olympics",
        "text": "Games Host city Dates Nations Participants Events 2008 Summer Olympics Beijing 8 -- 24 August 204 10,942 302 2022 Winter Olympics Beijing 4 -- 20 February",
        "triples": "<China at the Olympics; host city; Beijing>\n<China at the Olympics; 2008 Summer Olympics dates; 8 -- 24 August 204>\n<China at the Olympics; 2022 Winter Olympics dates; 4 -- 20 February>\n<China at the Olympics; 2008 Summer Olympics nations; 204>\n<China at the Olympics; 2008 Summer Olympics participants; 10,942>\n<China at the Olympics; 2008 Summer Olympics events; 302>", 
    },
    {
        "title": "The Heart That You Own",
        "text": "\"The Heart That You Own\" is a song written and recorded by American country music artist Dwight Yoakam. It was released in April 1992 as the fifth single from his album \"If There Was a Way\". This song peaked at number 18 in the United States and at number 13 in Canada.",
        "triples": "<The Heart That You Own; type; song>\n<The Heart That You Own; writer and performer; American country music artist Dwight Yoakam>\n<The Heart That You Own; release date; April 1992>\n<The Heart That You Own; album; fifth single from the album \"If There Was a Way\">\n<The Heart That You Own; peak position in the United States; number 18>\n<The Heart That You Own; peak position in Canada; number 13>", 
    },
    # 41 - 45
    {
        "title": "Ducharme Bridge",
        "text": "The Ducharme Bridge (French: \"Pont Ducharme\") is a covered bridge with a lattice truss structure, which crosses the Bostonnais River in the center of La Bostonnais, Quebec. The bridge was built in 1946 and it is long. It was classified as a historic monument in 2006, because it was a late example of an elaborated town bridge, a truss developed by the Departement of colonization of Quebec at the turn of the 20th century. It was named after Romulus Ducharme, MLA of Laviolette in 1936-1939 and 1944-1966.",
        "triples": "<Ducharme Bridge; French name; Pont Ducharme>\n<Ducharme Bridge; type; covered bridge with a lattice truss structure>\n<Ducharme Bridge; river that the bridge spans; Bostonnais River>\n<Ducharme Bridge; location; center of La Bostonnais, Quebec>\n<Ducharme Bridge; built year; 1946>\n<Ducharme Bridge; the year when the bridge was classified as a historic monument; 2006>\n<Ducharme Bridge; reason why the bridge was classified as a historic monument; late example of an elaborated town bridge truss>\n<Ducharme Bridge; truss developer; Departement of colonization of Quebec>\n<Ducharme Bridge; name after; Romulus Ducharme>\n<Ducharme Bridge; position held by Romulus Ducharme; MLA of Laviolette in 1936-1939 and 1944-1966>", 
    },
    {
        "title": "Dave's World",
        "text": "Dave's World Dave's World intertitle Created by Fred Barron Based on the books Dave Barry's Greatest Hits and Dave Barry Turns 40 by Dave Barry Starring Harry Anderson DeLane Matthews Zane Carney Andrew Ducote Shadoe Stevens Meshach Taylor J.C. Wendel Opening theme ``You May Be Right ''by Southside Johnny Country of origin United States Original language (s) English No. of seasons No. of episodes 98 Production Executive producer (s) Jonathan Axelrod Fred Barron Producer (s) Faye Oshima Belyeu Running time 30 minutes Production company (s) Producers Entertainment Group Ltd. Axelrod - Widdoes Productions Fred Barron Productions (1993 - 1995) (seasons 1 - 2) Livestock Productions (1993 - 1995) (seasons 1 - 2) Kitten in the Oven Productions (1995 - 1997) (seasons 3 - 4) CBS Productions Distributor CBS Television Distribution Release Original network CBS Original release September 20, 1993 -- July 18, 1997",
        "triples": "<Dave's World; created by; Fred Barron>\n<Dave's World; based on; Dave Barry's Greatest Hits and Dave Barry Turns 40 by Dave Barry>\n<Dave's World; main actors; Harry Anderson, DeLane Matthews, Zane Carney, Andrew Ducote, Shadoe Stevens, Meshach Taylor, J.C. Wendel>\n<Dave's World; opening theme; You May Be Right by Southside Johnny>\n<Dave's World; country of origin; United States>\n<Dave's World; original language; English>\n<Dave's World; number of episodes; 98>\n<Dave's World; executive producers; Jonathan Axelrod and Fred Barron>\n<Dave's World; producers; Faye Oshima Belyeu>\n<Dave's World; running time; 30 minutes>\n<Dave's World; production companies; Producers Entertainment Group Ltd., Axelrod-Widdoes Productions, Fred Barron Productions, Livestock Productions, Kitten in the Oven Productions, CBS Productions>\n<Dave's World; distributor; CBS Television Distribution>\n<Dave's World; network that originally aired the show; CBS>\n<Dave's World; original release dates; September 20, 1993 -- July 18, 1997>", 
    },
    {
        "title": "Bob Hess",
        "text": "Robert George Hess (born May 19, 1955 in Middleton, Nova Scotia) is a Canadian retired professional ice hockey defenceman. He played in the National Hockey League for the St. Louis Blues, Buffalo Sabres, and Hartford Whalers. Between 1982 and 1984 Hess played in Switzerland's Nationalliga A for HC Lugano and EHC Kloten.",
        "triples": "<Bob Hess; full name; Robert George Hess>\n<Bob Hess; date of birth; May 19, 1955>\n<Bob Hess; place of birth; Middleton, Nova Scotia>\n<Bob Hess; nationality; Canadian>\n<Bob Hess; occupation; retired professional ice hockey defenceman>\n<Bob Hess; teams he played for in the National Hockey League; St. Louis Blues, Buffalo Sabres, and Hartford Whalers>\n<Bob Hess; teams he played for in Switzerland's Nationalliga A; HC Lugano and EHC Kloten>\n<Bob Hess; period he played in Switzerland's Nationalliga A; between 1982 and 1984>", 
    },
    {
        "title": "Oklahoma City",
        "text": "Oklahoma City is the capital and largest city of the state of Oklahoma. The county seat of Oklahoma County, the city ranks 27th among United States cities in population. The population grew following the 2010 Census, with the population estimated to have increased to 620,602 as of July 2014. As of 2014, the Oklahoma City metropolitan area had a population of 1,322,429, and the Oklahoma City-Shawnee Combined Statistical Area had a population of 1,459,758 (Chamber of Commerce) residents, making it Oklahoma's largest metropolitan area. Oklahoma City's city limits extend into Canadian, Cleveland, and Pottawatomie counties, though much of those areas outside of the core Oklahoma County area are suburban or rural (watershed). The city ranks as the eighth-largest city in the United States by land area (including consolidated city-counties; it is the largest city in the United States by land area whose government is not consolidated with that of a county or borough).",
        "triples": "<Oklahoma City; status; capital and largest city of the state of Oklahoma>\n<Oklahoma City; county seat of; Oklahoma County>\n<Oklahoma City; population rank in the United States; 27th>\n<Oklahoma City; estimated population as of July 2014; 620,602>\n<Oklahoma City; population of the metropolitan area as of 2014; 1,322,429>\n<Oklahoma City; population of the Oklahoma City-Shawnee Combined Statistical Area; 1,459,758>\n<Oklahoma City; is largest metropolitan area in; Oklahoma>\n<Oklahoma City; city limits extend into; Canadian, Cleveland, and Pottawatomie counties>\n<Oklahoma City; areas outside core Oklahoma County; suburban or rural (watershed)>\n<Oklahoma City; land area rank in the United States; eighth-largest city>\n<Oklahoma City; largest city by land area; not consolidated with a county or borough>", 
    },
    {
        "title": "Cass, West Virginia",
        "text": "Cass is a census-designated place (CDP) on the Greenbrier River in Pocahontas County, West Virginia, USA. As of the 2010 census, its population was 52. The town, founded in 1901, was named for Joseph Kerr Cass, vice president and cofounder of the West Virginia Pulp and Paper Company.",
        "triples": "<Cass, West Virginia; type; census-designated place (CDP)>\n<Cass, West Virginia; location; on the Greenbrier River in Pocahontas County, West Virginia, USA>\n<Cass, West Virginia; population as of the 2010 census; 52>\n<Cass, West Virginia; the time when the town was founded; 1901>\n<Cass, West Virginia; name after; Joseph Kerr Cass, vice president and cofounder of the West Virginia Pulp and Paper Company>", 
    },
    # 46 - 50 
    {
        "title": "Journal of Creative Behavior",
        "text": "The Journal of Creative Behavior is a quarterly peer-reviewed academic journal published by Wiley-Blackwell on behalf of the Creative Education Foundation. The journal was established in 1967. Its current editor-in-chief is Ronald A. Beghetto (University of Connecticut). The journal focuses on creativity and problem solving, including ways to foster creative productivity, giftedness, management of creative personnel, testing, creativity in business and industry, development of creative curricula, and creativity in the arts and the sciences.",
        "triples": "<Journal of Creative Behavior; publish frequency; quarterly>\n<Journal of Creative Behavior; type; peer-reviewed academic journal>\n<Journal of Creative Behavior; publisher; Wiley-Blackwell on behalf of the Creative Education Foundation>\n<Journal of Creative Behavior; the year when the journal was established; 1967>\n<Journal of Creative Behavior; current editor-in-chief; Ronald A. Beghetto (University of Connecticut)>\n<Journal of Creative Behavior; focus areas; creativity and problem solving>\n<Journal of Creative Behavior; included topics; ways to foster creative productivity, giftedness, management of creative personnel, testing, creativity in business and industry, development of creative curricula, and creativity in the arts and the sciences>", 
    },
    {
        "title": "Union territory",
        "text": "A union territory is a type of administrative division in the Republic of India. Unlike states, which have their own elected governments, union territories are ruled directly by the Union Government (central government), hence the name ``union territory ''. Union territories in India qualify as federal territories, by definition.",
        "triples": "<Union territory; type; administrative division in the Republic of India>\n<Union territory; governance; ruled directly by the Union Government (central government)>\n<Union territory; name origin; union territories are ruled directly by the Union Government>\n<Union territory; classification; federal territories>", 
    },
    {
        "title": "British Empire",
        "text": "During the Age of Discovery in the 15th and 16th centuries, Portugal and Spain pioneered European exploration of the globe, and in the process established large overseas empires. Envious of the great wealth these empires generated, England, France, and the Netherlands began to establish colonies and trade networks of their own in the Americas and Asia. A series of wars in the 17th and 18th centuries with the Netherlands and France left England (and then, following union between England and Scotland in 1707, Great Britain) the dominant colonial power in North America and India.",
        "triples": "<British Empire; period of establishment; Age of Discovery in the 15th and 16th centuries>\n<British Empire; why England began to establish colonies; envy of great wealth generated by Portuguese and Spanish empires>\n<British Empire; competitors; France and the Netherlands>\n<British Empire; areas where England established colonies and trade networks; Americas and Asia>\n<British Empire; result of wars with the Netherlands and France; dominant colonial power in North America and India>\n<British Empire; union between England and Scotland; 1707>", 
    },
    {
        "title": "Flip and Flop",
        "text": "Flip and Flop is an isometric platform game for the Atari 8-bit family designed by Jim Nangano and published in 1983 by First Star Software. Statesoft released a Commodore 64 port the following year. The Commodore 64 box cover, which features a photo of acrobats that does not relate to the game itself, changes the name to Flip & Flop; it remains \"Flip and Flop\" on the title screen.",
        "triples": "<Flip and Flop; type; isometric platform game>\n<Flip and Flop; platform; Atari 8-bit family>\n<Flip and Flop; designer; Jim Nangano>\n<Flip and Flop; publisher; First Star Software>\n<Flip and Flop; release year; 1983>\n<Flip and Flop; company that released the Commodore 64 version; Statesoft>\n<Flip and Flop; Commodore 64 port release year; 1984>\n<Flip and Flop; Commodore 64 box cover photo; acrobats>\n<Flip and Flop; Commodore 64 box cover name; Flip & Flop>\n<Flip and Flop; title screen name; Flip and Flop>", 
    },
    {
        "title": "Prime Minister of India",
        "text": "Prime Minister of the Government of India State Emblem of India Flag of India Incumbent Narendra Modi since 26 May 2014 (2014 - 05 - 26) Prime Minister's Office Style The Honourable (formal) His Excellency (in diplomatic correspondence) Status Head of government Abbreviation PM Member of Cabinet, parliament Residence 7, Lok Kalyan Marg, New Delhi Seat Prime Minister's Office, South Block, New Delhi Appointer President of India by convention, based on appointee's ability to command confidence in the Lok Sabha Term length At the pleasure of the president Lok Sabha term is 5 years unless dissolved sooner No term limits specified Inaugural holder Jawaharlal Nehru (1947 - 1964) Formation 15 August 1947; 70 years ago (1947 - 08 - 15) Deputy Deputy Prime Minister of India (if any) Salary \u20b920 lakh (US $31,000) (annual, including \u20b9960,000 (US $15,000) MP's salary) Website pmindia.gov.in",
        "triples": "<Prime Minister of India; state emblem; State Emblem of India>\n<Prime Minister of India; flag; Flag of India>\n<Prime Minister of India; incumbent; Narendra Modi>\n<Prime Minister of India; the date when the current prime minister took office; since 26 May 2014>\n<Prime Minister of India; formal style; The Honourable>\n<Prime Minister of India; diplomatic style; His Excellency>\n<Prime Minister of India; status; Head of government>\n<Prime Minister of India; abbreviation; PM>\n<Prime Minister of India; membership; Cabinet, parliament>\n<Prime Minister of India; residence; 7, Lok Kalyan Marg, New Delhi>\n<Prime Minister of India; location of the prime minister's office; Prime Minister's Office, South Block, New Delhi>\n<Prime Minister of India; appointer; President of India>\n<Prime Minister of India; term length; at the pleasure of the president>\n<Prime Minister of India; legislative term; 5 years>\n<Prime Minister of India; term limits; no term limits specified>\n<Prime Minister of India; inaugural holder; Jawaharlal Nehru>\n<Prime Minister of India; formation date; 15 August 1947>\n<Prime Minister of India; deputy; Deputy Prime Minister of India>\n<Prime Minister of India; annual salary; \u20b920 lakh (US $31,000) (annual, including \u20b9960,000 (US $15,000) MP's salary)>\n<Prime Minister of India; website; pmindia.gov.in>", 
    }
]

